#Libraries

In [ ]:
# Base -----------------------------------
import pathlib
import sys
import pandas as pd
import numpy as np
import datetime as dt
import seaborn as sns
from datetime import *
#para mostrar todas las columnas de la tabla
pd.set_option('display.max_columns', None)

In [ ]:
# Viz ------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
from plotnine import *
plt.style.use('seaborn')

<ipython-input-2-e7415da9f2bc>:5: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Propose standardization
standardization_map = {
        'Andalucia': 'Andalusia',
        'Andalucía': 'Andalusia',
        'Aragón': 'Aragon',
		    'Asturias (Principado de)': 'Asturias',
        'BalearicIslands': 'Balearic Islands',
		    'Balears (Illes)': 'Balearic Islands',
        'BasqueCountry': 'Basque Country',
		    'País Vasco': 'Basque Country',
        'Canarias': 'Canary Islands',
        'CanaryIslands':'Canary Islands',
        'CastileandLeón': 'Castile and León',
        'Castilla y Leon': 'Castile and León',
        'CastileLaMancha': 'Castile-La Mancha',
        'Castilla-La Mancha': 'Castile-La Mancha',
        'Cataluña': 'Catalonia',
        'Madrid (Comunidad de)': 'Madrid',
        'LaRioja': 'La Rioja',
		    'Rioja (La)': 'La Rioja',
        'Rioja': 'La Rioja',
        'Navarra': 'Navarre',
		    'Navarra (Comunidad Foral de)': 'Navarre',
		    'Comunitat Valenciana': 'Valencian Region',
        'ValencianCommunity': 'Valencian Region',
		    'Murcia (Región de)': 'Murcia'
}

#Import Dataset

#Oil Products Consumption by Region Year & Month

In [ ]:
# Sharedrive file
file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/oil-products-consumption-autonomous-regions-provinces.csv'

# second sheet to be uploaded
df = pd.read_csv(file_path)

In [ ]:
df.head(10)

,Year,Month,Region,Province,Gasoline 95 RON,Gasoline 98 RON,Road diesel,Agricultural diesel,Heating oil,Low-sulphur fuel oil,Total Consumption,Diesel Consumption,Gasoline Consumption
0,2014,April,Andalusia,AlmeriaCadizCordobaGranadaHuelvaJaenMalagaSeville,55981.86,1989.40,266259.13,44291.15,12703.45,5491.47,386716.46,328745.20,57971.26
1,2014,April,Aragon,HuescaTeruelZaragoza,10645.77,517.00,74528.28,17977.28,5535.52,316.58,109520.43,98357.66,11162.77
2,2014,April,Asturias,Asturias,7190.79,508.89,36574.42,6124.99,4209.55,3875.00,58483.64,50783.96,7699.68
3,2014,April,Balearic Islands,Balearic Islands,16000.96,905.20,29258.00,3064.22,13368.79,7310.87,69908.04,53001.88,16906.16
4,2014,April,Basque Country,AlavaGuipuzcoaVizcaya,14184.43,934.18,126651.43,10315.03,6025.53,575.16,158685.76,143567.15,15118.61
5,2014,April,Canary Islands,Las PalmasSta. Cruz Tenerife,30297.34,9944.53,51411.81,0.00,0.00,64532.47,156186.15,115944.28,40241.87
6,2014,April,Cantabria,Cantabria,4800.51,260.95,24432.95,3765.77,961.85,403.76,34625.79,29564.33,5061.46
7,2014,April,Castilla y Leon,AvilaBurgosLeonPalenciaSalamancaSegoviaSoriaVa...,20123.82,993.55,121015.14,45342.90,17230.32,1060.10,205765.83,184648.46,21117.37
8,2014,April,Castilla-La Mancha,AlbaceteCiudad RealCuencaGuadalajaraToledo,14305.59,603.79,97562.26,32652.72,8039.69,5785.42,158949.47,144040.09,14909.38
9,2014,April,Catalonia,BarcelonaGeronaLeridaTarragona,58888.48,3724.01,267366.01,28873.94,11877.49,1762.97,372492.90,309880.41,62612.49

In [ ]:
# Create a new DataFrame with selected columns
df_consumption = df[['Year', 'Month', 'Region', 'Total Consumption', 'Diesel Consumption', 'Gasoline Consumption']]
df_consumption.head()

,Year,Month,Region,Total Consumption,Diesel Consumption,Gasoline Consumption
0,2014,April,Andalusia,386716.46,328745.20,57971.26
1,2014,April,Aragon,109520.43,98357.66,11162.77
2,2014,April,Asturias,58483.64,50783.96,7699.68
3,2014,April,Balearic Islands,69908.04,53001.88,16906.16
4,2014,April,Basque Country,158685.76,143567.15,15118.61

In [ ]:
df_consumption.columns = df_consumption.columns.str.lower()
df_consumption.columns = df_consumption.columns.str.replace (" ", "_")
df_consumption.head()

,year,month,region,total_consumption,diesel_consumption,gasoline_consumption
0,2014,April,Andalusia,386716.46,328745.20,57971.26
1,2014,April,Aragon,109520.43,98357.66,11162.77
2,2014,April,Asturias,58483.64,50783.96,7699.68
3,2014,April,Balearic Islands,69908.04,53001.88,16906.16
4,2014,April,Basque Country,158685.76,143567.15,15118.61

In [ ]:
df_consumption.region.unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Basque Country', 'Canary Islands', 'Cantabria', 'Castilla y Leon',
       'Castilla-La Mancha', 'Catalonia', 'Ceuta', 'Extremadura',
       'Galicia', 'La Rioja', 'Madrid', 'Melilla', 'Murcia', 'Navarra',
       'Valencian Region'], dtype=object)

In [ ]:
# Apply proposed standardization to result
df_consumption['region'] = df_consumption['region'].replace(standardization_map)

<ipython-input-10-10195d14f36c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# IPC & Brent Prices by Year & Month

In [ ]:
# Sharedrive file
file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/IPC_Brent_pricesgasoleum_gasoil.csv'

# second sheet to be uploaded
df_prices = pd.read_csv(file_path)

In [ ]:
df_prices.head()

,Year_Month,Diesel,Gasoline,Year,Month,Diesel_withouttaxes,Gasoline_withoutaxes,LastBrentPrice
0,2024-04-01,121.849,119.152,2024,4,73.1094,71.4912,"86,33"
1,2024-03-01,121.013,115.430,2024,3,72.6078,69.2580,"87,48"
2,2024-02-01,121.817,112.570,2024,2,73.0902,67.5420,"81,91"
3,2024-01-01,117.262,108.874,2024,1,70.3572,65.3244,"80,55"
4,2023-12-01,118.129,108.366,2023,12,70.8774,65.0196,"77,04"

In [ ]:
df_prices.columns = df_prices.columns.str.lower()
df_prices.columns = df_prices.columns.str.replace (" ", "_")
df_prices.head()

,year_month,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice
0,2024-04-01,121.849,119.152,2024,4,73.1094,71.4912,"86,33"
1,2024-03-01,121.013,115.430,2024,3,72.6078,69.2580,"87,48"
2,2024-02-01,121.817,112.570,2024,2,73.0902,67.5420,"81,91"
3,2024-01-01,117.262,108.874,2024,1,70.3572,65.3244,"80,55"
4,2023-12-01,118.129,108.366,2023,12,70.8774,65.0196,"77,04"

In [ ]:
# Convert 'Year_Month' in df2 to datetime
df_prices['year_month'] = pd.to_datetime(df_prices['year_month']).dt.date
df_prices.head()

,year_month,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice
0,2024-04-01,121.849,119.152,2024,4,73.1094,71.4912,"86,33"
1,2024-03-01,121.013,115.430,2024,3,72.6078,69.2580,"87,48"
2,2024-02-01,121.817,112.570,2024,2,73.0902,67.5420,"81,91"
3,2024-01-01,117.262,108.874,2024,1,70.3572,65.3244,"80,55"
4,2023-12-01,118.129,108.366,2023,12,70.8774,65.0196,"77,04"

In [ ]:
# # Add 'Year_Month' column to new_df
df_consumption['year_month'] = pd.to_datetime(df_consumption['year'].astype(str) + '-' + df_consumption['month'].astype(str) + '-01').dt.date
print(df_consumption['year_month'].dtype)

object

<ipython-input-15-a6c5072501f8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df_consumption.columns

Index(['year', 'month', 'region', 'total_consumption', 'diesel_consumption',
       'gasoline_consumption', 'year_month'],
      dtype='object')

In [ ]:
# Merge df_consumption and df_prices on 'Year_Month'
merged_df = pd.merge(df_consumption[['year_month', 'region','total_consumption', 'diesel_consumption','gasoline_consumption']], df_prices, on='year_month', how='inner')

# # Identify missing data in the merged DataFrame
missing_data_dates = df_prices[df_prices.isna().any(axis=1)]['year_month'].unique()
print("Year_Month values with missing data in df_prices:")
print(missing_data_dates)

Year_Month values with missing data in df_prices:
[datetime.date(2016, 12, 1) datetime.date(2016, 11, 1)
 datetime.date(2016, 10, 1) datetime.date(2016, 9, 1)
 datetime.date(2016, 8, 1) datetime.date(2016, 7, 1)
 datetime.date(2016, 6, 1) datetime.date(2016, 5, 1)
 datetime.date(2016, 4, 1) datetime.date(2016, 3, 1)
 datetime.date(2016, 2, 1) datetime.date(2016, 1, 1)
 datetime.date(2015, 12, 1) datetime.date(2015, 11, 1)
 datetime.date(2015, 10, 1) datetime.date(2015, 9, 1)
 datetime.date(2015, 8, 1) datetime.date(2015, 7, 1)
 datetime.date(2015, 6, 1) datetime.date(2015, 5, 1)
 datetime.date(2015, 4, 1) datetime.date(2015, 3, 1)
 datetime.date(2015, 2, 1) datetime.date(2015, 1, 1)
 datetime.date(2014, 12, 1) datetime.date(2014, 11, 1)
 datetime.date(2014, 10, 1) datetime.date(2014, 9, 1)
 datetime.date(2014, 8, 1) datetime.date(2014, 7, 1)
 datetime.date(2014, 6, 1) datetime.date(2014, 5, 1)
 datetime.date(2014, 4, 1) datetime.date(2014, 3, 1)
 datetime.date(2014, 2, 1) datetime.date(2014, 1, 1)]

In [ ]:
merged_df.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,2014,4,NaN,NaN,"108,07"
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,2014,4,NaN,NaN,"108,07"
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,2014,4,NaN,NaN,"108,07"
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,2014,4,NaN,NaN,"108,07"
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,2014,4,NaN,NaN,"108,07"

In [ ]:
# merged_df.tail()

In [ ]:
if not isinstance(merged_df, pd.DataFrame):
    merged_df = pd.DataFrame(merged_df)

In [ ]:
merged_df.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,2014,4,NaN,NaN,"108,07"
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,2014,4,NaN,NaN,"108,07"
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,2014,4,NaN,NaN,"108,07"
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,2014,4,NaN,NaN,"108,07"
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,2014,4,NaN,NaN,"108,07"

In [ ]:
merged_df.region.unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Basque Country', 'Canary Islands', 'Cantabria',
       'Castile and León', 'Castile-La Mancha', 'Catalonia', 'Ceuta',
       'Extremadura', 'Galicia', 'La Rioja', 'Madrid', 'Melilla',
       'Murcia', 'Navarre', 'Valencian Region'], dtype=object)

# Import Weather by Region

In [ ]:
# Sharedrive file

file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/combined_weather_data.csv'

# second sheet to be uploaded
dfw = pd.read_csv(file_path)

In [ ]:
dfw.columns = dfw.columns.str.lower()
dfw.columns = dfw.columns.str.replace (" ", "_")
dfw.head()

,date,autonomous_region,largest_city,population,apparent_temperature_max,apparent_temperature_min,precipitation_sum,wind_speed_10m_max,sunshine_duration,snowfall_sum
0,2020-12-31 22:00:00+00:00,Andalusia,Seville,688711,9.167772,2.862932,0.5,16.179985,28301.453,0.0
1,2021-01-01 22:00:00+00:00,Andalusia,Seville,688711,8.581984,-1.363906,0.0,10.002560,31260.252,0.0
2,2021-01-02 22:00:00+00:00,Andalusia,Seville,688711,8.863238,-2.869949,0.0,11.966954,31308.070,0.0
3,2021-01-03 22:00:00+00:00,Andalusia,Seville,688711,9.713763,-1.067630,0.1,10.195057,31359.209,0.0
4,2021-01-04 22:00:00+00:00,Andalusia,Seville,688711,9.154552,0.022236,0.0,11.200571,21955.596,0.0

Standarize name of the region

In [ ]:
# Rename the column 'autonomous_region' to 'Region'
dfw.rename(columns={'autonomous_region': 'region'}, inplace=True)

dfw['region'] = dfw['region'].replace(standardization_map)

In [ ]:
dfw.region.unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Basque Country', 'Canary Islands', 'Cantabria',
       'Castile and León', 'Castile-La Mancha', 'Catalonia',
       'Extremadura', 'Galicia', 'La Rioja', 'Madrid', 'Murcia',
       'Navarre', 'Valencian Region'], dtype=object)

In [ ]:
# Round 'apparent_temperature_max' to 2 decimals
dfw['apparent_temperature_max'] = dfw['apparent_temperature_max'].round(2)

In [ ]:
dfw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151096 entries, 0 to 151095
Data columns (total 10 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   date                      151096 non-null  object
 1   region                    151096 non-null  object
 2   largest_city              151096 non-null  object
 3   population                151096 non-null  int64
 4   apparent_temperature_max  151096 non-null  float64
 5   apparent_temperature_min  151096 non-null  float64
 6   precipitation_sum         151096 non-null  float64
 7   wind_speed_10m_max        151096 non-null  float64
 8   sunshine_duration         151096 non-null  float64
 9   snowfall_sum              151096 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 11.5+ MB

In [ ]:
# Convert 'date' column to datetime format
dfw['date'] = pd.to_datetime(dfw['date'])

# Create 'Year_Month' column from 'date' column
dfw['year_month'] = dfw['date'].dt.to_period('M')

<ipython-input-29-f9542e19bfc3>:5: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.

In [ ]:
# Group by 'Region' and 'Year_Month', calculate the average of 'apparent_temperature_max'
result = dfw.groupby(['region', 'year_month'], as_index=False)['apparent_temperature_max'].mean()
# Print the result
result.head()

      region year_month  apparent_temperature_max
0  Andalusia    1999-12                 12.390000
1  Andalusia    2000-01                 12.680000
2  Andalusia    2000-02                 19.572414
3  Andalusia    2000-03                 20.610000
4  Andalusia    2000-04                 16.978333

In [ ]:
# Add missing regions 'Melilla' and 'Ceuta' to result
missing_regions = ['Melilla', 'Ceuta']
missing_df = pd.DataFrame({'region': missing_regions})
result = pd.concat([result, missing_df], ignore_index=True)
result.head()

      region year_month  apparent_temperature_max
0  Andalusia    1999-12                 12.390000
1  Andalusia    2000-01                 12.680000
2  Andalusia    2000-02                 19.572414
3  Andalusia    2000-03                 20.610000
4  Andalusia    2000-04                 16.978333

In [ ]:
merged_df.region.unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Basque Country', 'Canary Islands', 'Cantabria',
       'Castile and León', 'Castile-La Mancha', 'Catalonia', 'Ceuta',
       'Extremadura', 'Galicia', 'La Rioja', 'Madrid', 'Melilla',
       'Murcia', 'Navarre', 'Valencian Region'], dtype=object)

In [ ]:
result.region.unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Basque Country', 'Canary Islands', 'Cantabria',
       'Castile and León', 'Castile-La Mancha', 'Catalonia',
       'Extremadura', 'Galicia', 'La Rioja', 'Madrid', 'Murcia',
       'Navarre', 'Valencian Region', 'Melilla', 'Ceuta'], dtype=object)

In [ ]:
result['apparent_temperature_max'] = result['apparent_temperature_max'].round(2)

In [ ]:
result.head(5)

      region year_month  apparent_temperature_max
0  Andalusia    1999-12                     12.39
1  Andalusia    2000-01                     12.68
2  Andalusia    2000-02                     19.57
3  Andalusia    2000-03                     20.61
4  Andalusia    2000-04                     16.98

In [ ]:
# Filter data from 2014 onwards
df_weather_filtered = result[result['year_month'] >= pd.Period('2014', freq='M')].copy()

# Verify the information of new_df
df_weather_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2108 entries, 169 to 4980
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   region                    2108 non-null   object
 1   year_month                2108 non-null   period[M]
 2   apparent_temperature_max  2108 non-null   float64
dtypes: float64(1), object(1), period[M](1)
memory usage: 65.9+ KB

In [ ]:
df_weather_filtered.head(5)

        region year_month  apparent_temperature_max
169  Andalusia    2014-01                     13.67
170  Andalusia    2014-02                     13.45
171  Andalusia    2014-03                     18.27
172  Andalusia    2014-04                     24.56
173  Andalusia    2014-05                     28.14

In [ ]:
df_weather_filtered.year_month.min()

Period('2014-01', 'M')

In [ ]:
df_weather_filtered.year_month.max()

Period('2024-04', 'M')

### Join dataframe "merge_df" (consumption & prices) with "weather" filtered dataframe

In [ ]:
# # Create DataFrames
# merged_df = pd.DataFrame(merged_df)
# df_weather_filtered = pd.DataFrame(df_weather_filtered)

# Display the initial DataFrames
print("Initial merged_df:")
merged_df.head()

Initial merged_df:

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,2014,4,NaN,NaN,"108,07"
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,2014,4,NaN,NaN,"108,07"
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,2014,4,NaN,NaN,"108,07"
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,2014,4,NaN,NaN,"108,07"
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,2014,4,NaN,NaN,"108,07"

In [ ]:
print("\nInitial df_weather_filtered:")
df_weather_filtered.head()

Initial df_weather_filtered:

        region year_month  apparent_temperature_max
169  Andalusia    2014-01                     13.67
170  Andalusia    2014-02                     13.45
171  Andalusia    2014-03                     18.27
172  Andalusia    2014-04                     24.56
173  Andalusia    2014-05                     28.14

In [ ]:
merged_result.head(10)

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,2014,4,NaN,NaN,"108,07",24.56
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,2014,4,NaN,NaN,"108,07",19.90
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,2014,4,NaN,NaN,"108,07",15.34
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,2014,4,NaN,NaN,"108,07",20.76
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,2014,4,NaN,NaN,"108,07",14.32
5,2014-04-01,Canary Islands,156186.15,115944.28,40241.87,NaN,NaN,2014,4,NaN,NaN,"108,07",22.43
6,2014-04-01,Cantabria,34625.79,29564.33,5061.46,NaN,NaN,2014,4,NaN,NaN,"108,07",16.52
7,2014-04-01,Castile and León,205765.83,184648.46,21117.37,NaN,NaN,2014,4,NaN,NaN,"108,07",16.83
8,2014-04-01,Castile-La Mancha,158949.47,144040.09,14909.38,NaN,NaN,2014,4,NaN,NaN,"108,07",20.54
9,2014-04-01,Catalonia,372492.90,309880.41,62612.49,NaN,NaN,2014,4,NaN,NaN,"108,07",19.70

In [ ]:
merged_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year_month                2318 non-null   object
 1   region                    2318 non-null   object
 2   total_consumption         2318 non-null   float64
 3   diesel_consumption        2318 non-null   float64
 4   gasoline_consumption      2318 non-null   float64
 5   diesel                    1634 non-null   float64
 6   gasoline                  1634 non-null   float64
 7   year                      2318 non-null   int64
 8   month                     2318 non-null   int64
 9   diesel_withouttaxes       1634 non-null   float64
 10  gasoline_withoutaxes      1634 non-null   float64
 11  lastbrentprice            2318 non-null   object
 12  apparent_temperature_max  2074 non-null   float64
dtypes: float64(8), int64(2), object(3)
memory usage: 235.5+ KB

In [ ]:
# Drive Folder
csv_file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/Merged_oilcom_prices_weather.csv'

# csv file for oilconsumption CCAA
merged_result.to_csv(csv_file_path, index=False)
print(f'DataFrame saved successfully to {csv_file_path}')

DataFrame saved successfully to /content/drive/Shareddrives/Clandestino /Repsol/NAN/Merged_oilcom_prices_weather.csv

# Holidays Import Data load

In [ ]:
# Sharedrive file
file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/holidays.csv'

# second sheet to be uploaded
df_holidays = pd.read_csv(file_path)

In [ ]:
df_holidays.columns = df_holidays.columns.str.lower()
df_holidays.columns = df_holidays.columns.str.replace (" ", "_")
df_holidays.head()

      region year_month  days_holidays
0  Andalusia    2014-01              2
1  Andalusia    2014-02              1
2  Andalusia    2014-04              2
3  Andalusia    2014-05              1
4  Andalusia    2014-08              1

In [ ]:
df_holidays.region.unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Basque Country', 'Canary Islands', 'Cantabria',
       'Castile and Leon', 'Castile-La Mancha', 'Catalonia',
       'Extremadura', 'Galicia', 'La Rioja', 'Madrid', 'Murcia',
       'Navarre', 'Valencian Community'], dtype=object)

In [ ]:
df_holidays.head()

      region year_month  days_holidays
0  Andalusia    2014-01              2
1  Andalusia    2014-02              1
2  Andalusia    2014-04              2
3  Andalusia    2014-05              1
4  Andalusia    2014-08              1

In [ ]:
print(merged_result['region'].unique())
print(df_holidays['region'].unique())

['Andalusia' 'Aragon' 'Asturias' 'Balearic Islands' 'Basque Country'
 'Canary Islands' 'Cantabria' 'Castile and León' 'Castile-La Mancha'
 'Catalonia' 'Ceuta' 'Extremadura' 'Galicia' 'La Rioja' 'Madrid' 'Melilla'
 'Murcia' 'Navarre' 'Valencian Region']
['Andalusia' 'Aragon' 'Asturias' 'Balearic Islands' 'Basque Country'
 'Canary Islands' 'Cantabria' 'Castile and Leon' 'Castile-La Mancha'
 'Catalonia' 'Extremadura' 'Galicia' 'La Rioja' 'Madrid' 'Murcia'
 'Navarre' 'Valencian Community']

In [ ]:
# Drive Folder
csv_file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/Merged_oilcom_prices_weather_holidays.csv'

# csv file for oilconsumption CCAA
merged_result2.to_csv(csv_file_path, index=False)

print(f'DataFrame saved successfully to {csv_file_path}')

DataFrame saved successfully to /content/drive/Shareddrives/Clandestino /Repsol/NAN/Merged_oilcom_prices_weather_holidays.csv

#Vehicle landscape

In [ ]:
# Sharedrive file
file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/vehiclelandscap_Year_CCAA_fueltype.csv'

# second sheet to be uploaded
df_vehicles = pd.read_csv(file_path)

In [ ]:
df_vehicles.columns = df_vehicles.columns.str.lower()
df_vehicles.columns = df_vehicles.columns.str.replace (" ", "_")
df_vehicles.head()

,year,region,truck_gasoline,truck_diesel,truck_other,truck_total,van_gasoline,van_diesel,van_other,van_total,bus_gasoline,bus_diesel,bus_other,bus_total,car_gasoline,car_diesel,car_other,car_total,motorcycle_gasoline,motorcycle_diesel,motorcycle_other,motorcycle_total,tractor_gasoline,tractor_diesel,tractor_other,tractor_total,other_vehicles_gasoline,other_vehicles_diesel,other_vehicles_other,other_vehicles_total,total_gasoline,total_diesel,total_other,total_total,bus_other2,comunidades\nautónomas,tractor_total.1
0,2014,Andalucía,75304,780821,78,856203,0,0,0,0,25,8302,31.0,8358,1461193,2274782,707,3736682,557295,222,745,558262,0,30937,0,30937.0,24270,51420,2361,78051,2118087,3146484,3922,5268493,NaN,NaN,NaN
1,2014,Aragón,14638,130926,42,145606,0,0,0,0,3,1501,3.0,1507,246748,320020,243,567011,67033,94,71,67198,0,8125,0,8125.0,4371,15621,1290,21282,332793,476287,1649,810729,NaN,NaN,NaN
2,2014,Asturias (Principado de),9154,79615,25,88794,0,0,0,0,6,1378,0.0,1384,193059,300414,97,493570,50137,87,45,50269,0,3850,0,3850.0,3899,8229,627,12755,256255,393573,794,650622,NaN,NaN,NaN
3,2014,Balears (Illes),23502,108213,24,131739,0,0,0,0,15,2356,12.0,2383,420355,231753,189,652297,113060,24,356,113440,0,1892,0,1892.0,1587,6361,193,8141,558519,350599,774,909892,NaN,NaN,NaN
4,2014,Canarias,60362,283673,40,344075,0,0,0,0,52,5246,1.0,5299,819127,189074,204,1008405,107550,55,190,107795,0,4081,0,4081.0,4900,13571,386,18857,991991,495700,821,1488512,NaN,NaN,NaN

In [ ]:
df_vehicles.region.unique()

array(['Andalucía', 'Aragón', 'Asturias (Principado de)',
       'Balears (Illes)', 'Canarias', 'Cantabria', 'Castilla y León',
       'Castilla-La Mancha', 'Cataluña', 'Comunitat Valenciana',
       'Extremadura', 'Galicia', 'Madrid (Comunidad de)',
       'Murcia (Región de)', 'Navarra (Comunidad Foral de)', 'País Vasco',
       'Rioja (La)', 'Ceuta y Melilla', nan], dtype=object)

In [ ]:
# Apply proposed standardization to result
df_vehicles['region'] = df_vehicles['region'].replace(standardization_map)

In [ ]:
# List of vehicle categories to process
vehicle_categories = ['truck', 'van', 'bus', 'car', 'motorcycle', 'tractor', 'total']

# Iterate over vehicle categories and create new columns for Gasoline and Diesel totals
for category in vehicle_categories:
    df_vehicles[f'{category}_gasoline_total'] = df_vehicles[f'{category}_gasoline']
    df_vehicles[f'{category}_diesel_total'] = df_vehicles[f'{category}_diesel']

# Create a new DataFrame with only 'Year', 'Region', and the new columns for Gasoline and Diesel totals
columns_to_keep = ['year', 'region'] + [f'{category}_gasoline_total' for category in vehicle_categories] + \
                                    [f'{category}_diesel_total' for category in vehicle_categories]
df_vehicles_cat = df_vehicles[columns_to_keep]

# Display the new DataFrame
df_vehicles_cat.head()

,year,region,truck_gasoline_total,van_gasoline_total,bus_gasoline_total,car_gasoline_total,motorcycle_gasoline_total,tractor_gasoline_total,total_gasoline_total,truck_diesel_total,van_diesel_total,bus_diesel_total,car_diesel_total,motorcycle_diesel_total,tractor_diesel_total,total_diesel_total
0,2014,Andalusia,75304,0,25,1461193,557295,0,2118087,780821,0,8302,2274782,222,30937,3146484
1,2014,Aragon,14638,0,3,246748,67033,0,332793,130926,0,1501,320020,94,8125,476287
2,2014,Asturias,9154,0,6,193059,50137,0,256255,79615,0,1378,300414,87,3850,393573
3,2014,Balearic Islands,23502,0,15,420355,113060,0,558519,108213,0,2356,231753,24,1892,350599
4,2014,Canary Islands,60362,0,52,819127,107550,0,991991,283673,0,5246,189074,55,4081,495700

In [ ]:

# Generate a new DataFrame new_dfv with Total Gasoline Total and Total Diesel Total
df_vehicles_filtered = df_vehicles_cat[['year', 'region', 'total_gasoline_total', 'total_diesel_total']]

# Display the new DataFrame new_dfv
df_vehicles_filtered.head()

   year            region  total_gasoline_total  total_diesel_total
0  2014         Andalusia               2118087             3146484
1  2014            Aragon                332793              476287
2  2014          Asturias                256255              393573
3  2014  Balearic Islands                558519              350599
4  2014    Canary Islands                991991              495700

In [ ]:

# Rellenar los valores faltantes con ceros
df_vehicles_filtered['total_gasoline_total'] = df_vehicles_filtered['total_gasoline_total'].fillna(0)
df_vehicles_filtered['total_diesel_total'] = df_vehicles_filtered['total_diesel_total'].fillna(0)
df_vehicles_filtered.head()

<ipython-input-65-3b133f8832fb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
<ipython-input-65-3b133f8832fb>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   year            region  total_gasoline_total  total_diesel_total
0  2014         Andalusia               2118087             3146484
1  2014            Aragon                332793              476287
2  2014          Asturias                256255              393573
3  2014  Balearic Islands                558519              350599
4  2014    Canary Islands                991991              495700

In [ ]:
# Generar los números de los meses
months = list(range(1, 13))

In [ ]:
# Crear un nuevo DataFrame con los números de los meses replicados para cada año
expanded_df = df_vehicles_filtered.loc[df_vehicles_filtered.index.repeat(len(months))].reset_index(drop=True)
expanded_df['month'] = months * len(df_vehicles_filtered)
expanded_df['total_gasoline_total'] = (expanded_df['total_gasoline_total'] / 12).round().astype(int)
expanded_df['total_diesel_total'] = (expanded_df['total_diesel_total'] / 12).round().astype(int)
expanded_df.head()

   year     region  total_gasoline_total  total_diesel_total  month
0  2014  Andalusia                176507              262207      1
1  2014  Andalusia                176507              262207      2
2  2014  Andalusia                176507              262207      3
3  2014  Andalusia                176507              262207      4
4  2014  Andalusia                176507              262207      5

In [ ]:
# Clean column names by stripping leading/trailing spaces
expanded_df.columns = expanded_df.columns.str.strip()

In [ ]:
expanded_df.columns

Index(['year', 'region', 'total_gasoline_total', 'total_diesel_total',
       'month'],
      dtype='object')

In [ ]:
expanded_df.head()

   year     region  total_gasoline_total  total_diesel_total  month
0  2014  Andalusia                176507              262207      1
1  2014  Andalusia                176507              262207      2
2  2014  Andalusia                176507              262207      3
3  2014  Andalusia                176507              262207      4
4  2014  Andalusia                176507              262207      5

In [ ]:
# # Add 'Year_Month' column to new_df
expanded_df['year_month'] = pd.to_datetime(expanded_df['year'].astype(str) + '-' + expanded_df['month'].astype(str).str.zfill(2) + '-01').dt.date

In [ ]:
print(expanded_df['year_month'].dtype)

object

In [ ]:
expanded_df = expanded_df.drop(columns=['year', 'month'])

In [ ]:
expanded_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1944 entries, 0 to 1943
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   region                648 non-null    object
 1   total_gasoline_total  1944 non-null   int64
 2   total_diesel_total    1944 non-null   int64
 3   year_month            1944 non-null   object
dtypes: int64(2), object(2)
memory usage: 60.9+ KB

In [ ]:
merged_result2.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,2014,4,NaN,NaN,"108,07",24.56,2.0
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,2014,4,NaN,NaN,"108,07",19.90,3.0
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,2014,4,NaN,NaN,"108,07",15.34,2.0
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,2014,4,NaN,NaN,"108,07",20.76,2.0
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,2014,4,NaN,NaN,"108,07",14.32,3.0

In [ ]:
print("Columnas en merged_result2:", merged_result2.columns)
print("Columnas en grouped_dfv:", expanded_df.head().columns)

Columnas en merged_result2: Index(['year_month', 'region', 'total_consumption', 'diesel_consumption',
       'gasoline_consumption', 'diesel', 'gasoline', 'year', 'month',
       'diesel_withouttaxes', 'gasoline_withoutaxes', 'lastbrentprice',
       'apparent_temperature_max', 'days_holidays'],
      dtype='object')
Columnas en grouped_dfv: Index(['region', 'total_gasoline_total', 'total_diesel_total', 'year_month'], dtype='object')

In [ ]:
# Realizar el merge basado en year_month, region_mapped, year y month
merged_final = pd.merge(merged_result2, expanded_df, on=['year_month', 'region'], how='left')
merged_final.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,year,month,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,total_gasoline_total,total_diesel_total
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,2014,4,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,2014,4,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,2014,4,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,2014,4,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,2014,4,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0

In [ ]:

# Eliminar las columnas adicionales que fueron temporales
merged_final.drop(['year', 'month'], axis=1, inplace=True)

merged_final.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,total_gasoline_total,total_diesel_total
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0

##FINAL MERGE FILE

In [ ]:
# Drive Folder
csv_file_path = '/content/drive/Shareddrives/Clandestino /Repsol/NAN/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape.csv'

# csv file for oilconsumption CCAA
merged_final.to_csv(csv_file_path, index=False)

print(f'DataFrame saved successfully to {csv_file_path}')

DataFrame saved successfully to /content/drive/Shareddrives/Clandestino /Repsol/NAN/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape.csv

In [ ]:
# Drive Folder
csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape.csv'

# csv file for oilconsumption CCAA
merged_final.to_csv(csv_file_path, index=False)

print(f'DataFrame saved successfully to {csv_file_path}')

DataFrame saved successfully to /content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape.csv

In [ ]:
merged_final.to_excel('/content/drive/Shareddrives/Clandestino /Repsol/NAN/check.xlsx', index=False)