#Libraries

In [ ]:
# Base -----------------------------------
import pathlib
import sys
import pandas as pd
import numpy as np
import datetime as dt
import seaborn as sns
from datetime import *
#para mostrar todas las columnas de la tabla
pd.set_option('display.max_columns', None)

In [ ]:
# Viz ------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
from plotnine import *
plt.style.use('seaborn')

<ipython-input-2-e7415da9f2bc>:5: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.

#Import Dataset FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_UnemRate_ipc

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Sharedrive file

file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_UnemRate.csv'

# second sheet to be uploaded
df = pd.read_csv(file_path)

In [ ]:
df.head(1000)

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,total_gasoline_total,total_diesel_total,UnemRate,IPC
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0,34.74,0.3
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0,20.83,0.1
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0,21.02,0.2
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0,19.04,0.6
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0,16.13,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-01-01,Castile and Le√≥n,246637.31,227659.29,18978.02,92.829,90.012,55.6974,54.0072,"69,05",5.60,NaN,NaN,NaN,NaN,NaN
996,2018-01-01,Castile-La Mancha,203714.10,190822.21,12891.89,92.829,90.012,55.6974,54.0072,"69,05",9.07,2.0,NaN,NaN,NaN,NaN
997,2018-01-01,Catalonia,434398.88,372869.86,61529.02,92.829,90.012,55.6974,54.0072,"69,05",13.01,2.0,NaN,NaN,12.19,0.9
998,2018-01-01,Ceuta,4257.05,3769.54,487.51,92.829,90.012,55.6974,54.0072,"69,05",NaN,NaN,NaN,NaN,31.44,-0.3
999,2018-01-01,Extremadura,72966.88,65882.06,7084.82,92.829,90.012,55.6974,54.0072,"69,05",11.58,2.0,NaN,NaN,25.94,0.2

# Import Dataset IPC Rate

In [ ]:
# Sharedrive file

file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/IPC_Region_Year_Month.csv'

# second sheet to be uploaded
df_ipc = pd.read_csv(file_path)

In [ ]:
df_ipc.head()

  year_month     Region  Value
0    2024-04  Andalusia    3.3
1    2024-03  Andalusia    3.1
2    2024-02  Andalusia    2.9
3    2024-01  Andalusia    3.8
4    2023-12  Andalusia    3.3

In [ ]:
df_ipc['region']=df_ipc['Region']

In [ ]:
df_ipc.region.unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Canary Islands', 'Cantabria', 'Castilla y Leon',
       'Castilla-La Mancha', 'Catalonia', 'Valencian Region',
       'Extremadura', 'Galicia', 'Madrid', 'Murcia', 'Navarre',
       'Basque Country', 'La Rioja', 'Ceuta', 'Melilla'], dtype=object)

In [ ]:
#df.region.unique()

In [ ]:
# # Add 'Year_Month' column to new_df
# Usar str.split para dividir la columna year_month
df_ipc[['year', 'month']] = df_ipc['year_month'].str.split('-', expand=True)

In [ ]:
df_ipc.head()

  year_month     Region  Value     region  year month
0    2024-04  Andalusia    3.3  Andalusia  2024    04
1    2024-03  Andalusia    3.1  Andalusia  2024    03
2    2024-02  Andalusia    2.9  Andalusia  2024    02
3    2024-01  Andalusia    3.8  Andalusia  2024    01
4    2023-12  Andalusia    3.3  Andalusia  2023    12

In [ ]:
# # Add 'Year_Month' column to new_df
df_ipc['year_month'] = pd.to_datetime(df_ipc['year'].astype(str) + '-' + df_ipc['month'].astype(str).str.zfill(2) + '-01').dt.date

In [ ]:
df_ipc.tail()

      year_month   Region  Value   region  year month
2351  2014-05-01  Melilla   -0.2  Melilla  2014    05
2352  2014-04-01  Melilla   -0.2  Melilla  2014    04
2353  2014-03-01  Melilla   -0.8  Melilla  2014    03
2354  2014-02-01  Melilla   -0.6  Melilla  2014    02
2355  2014-01-01  Melilla   -0.2  Melilla  2014    01

In [ ]:
df_ipc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year_month  2356 non-null   object
 1   Region      2356 non-null   object
 2   Value       2356 non-null   float64
 3   region      2356 non-null   object
 4   year        2356 non-null   object
 5   month       2356 non-null   object
dtypes: float64(1), object(5)
memory usage: 110.6+ KB

In [ ]:
df_ipc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year_month  2356 non-null   object
 1   Region      2356 non-null   object
 2   Value       2356 non-null   float64
 3   region      2356 non-null   object
 4   year        2356 non-null   object
 5   month       2356 non-null   object
dtypes: float64(1), object(5)
memory usage: 110.6+ KB

In [ ]:
# Crear el mapa de estandarizaci√≥n completo
standardization_map = {
    'Andalusia': 'Andalusia',
    'Aragon': 'Aragon',
    'Asturias': 'Asturias',
    'Balearic Islands': 'Balearic Islands',
    'Canary Islands': 'Canary Islands',
    'Cantabria': 'Cantabria',
    'Castilla y Leon': 'Castile and Le√≥n',
    'Castilla-La Mancha': 'Castile-La Mancha',
    'Catalonia': 'Catalonia',
    'Valencian Region': 'Valencian Region',
    'Extremadura': 'Extremadura',
    'Galicia': 'Galicia',
    'Madrid': 'Madrid',
    'Murcia': 'Murcia',
    'Navarra': 'Navarre',
    'Basque Country': 'Basque Country',
    'La Rioja': 'La Rioja',
    'Ceuta': 'Ceuta',
    'Melilla': 'Melilla'
}

# Aplicar el mapa de estandarizaci√≥n a df_desem
df_ipc['region_standardized'] = df_ipc['region'].map(standardization_map)

# Crear el mapa inverso para estandarizar df
inverse_standardization_map = {v: k for k, v in standardization_map.items()}
df_ipc['region_standardized'] = df_ipc['Region'].map(inverse_standardization_map)

In [ ]:
# Convertir year_month a datetime
df['year_month'] = pd.to_datetime(df['year_month'])
df_ipc['year_month'] = pd.to_datetime(df_ipc['year_month'])

# Verificar tipos de datos
print(df.dtypes)
print(df_ipc.dtypes)

year_month                  datetime64[ns]
region                              object
total_consumption                  float64
diesel_consumption                 float64
gasoline_consumption               float64
diesel                             float64
gasoline                           float64
diesel_withouttaxes                float64
gasoline_withoutaxes               float64
lastbrentprice                      object
apparent_temperature_max           float64
days_holidays                      float64
total_gasoline_total               float64
total_diesel_total                 float64
UnemRate                           float64
IPC                                float64
dtype: object
year_month             datetime64[ns]
Region                         object
Value                         float64
region                         object
year                           object
month                          object
region_standardized            object
dtype: object

In [ ]:
df_ipc = df_ipc[df_ipc['year_month'].dt.year >= 2014]

In [ ]:
# Crear el mapa de estandarizaci√≥n completo
standardization_map = {
    'Andalusia': 'Andalusia',
    'Aragon': 'Aragon',
    'Asturias': 'Asturias',
    'Balearic Islands': 'Balearic Islands',
    'Canary Islands': 'Canary Islands',
    'Cantabria': 'Cantabria',
    'Castilla y Leon': 'Castile and Le√≥n',
    'Castilla-La Mancha': 'Castile-La Mancha',
    'Catalonia': 'Catalonia',
    'Valencian Region': 'Valencian Region',
    'Extremadura': 'Extremadura',
    'Galicia': 'Galicia',
    'Madrid': 'Madrid',
    'Murcia': 'Murcia',
    'Navarra': 'Navarre',
    'Basque Country': 'Basque Country',
    'La Rioja': 'La Rioja',
    'Ceuta': 'Ceuta',
    'Melilla': 'Melilla'
}

# Aplicar el mapa de estandarizaci√≥n a df_desem
df_ipc['region_standardized'] = df_ipc['region'].map(standardization_map)

# Crear el mapa inverso para estandarizar df
inverse_standardization_map = {v: k for k, v in standardization_map.items()}
df['region_standardized'] = df['region'].map(inverse_standardization_map)

# Convertir year_month a datetime
df['year_month'] = pd.to_datetime(df['year_month'])
df_ipc['year_month'] = pd.to_datetime(df_ipc['year_month'])

# Realizar la uni√≥n usando las columnas estandarizadas y year_month
merged_final = pd.merge(df, df_ipc[['year_month', 'region_standardized']],
                        left_on=['year_month', 'region_standardized'],
                        right_on=['year_month', 'region_standardized'],
                        how='left')

# Eliminar la columna temporal 'region_standardized' si ya no es necesaria
merged_final.drop(columns=['region_standardized'], inplace=True)

# Mostrar el resultado
print(merged_final.head())

  year_month            region  total_consumption  diesel_consumption  \
0 2014-04-01         Andalusia          386716.46           328745.20
1 2014-04-01            Aragon          109520.43            98357.66
2 2014-04-01          Asturias           58483.64            50783.96
3 2014-04-01  Balearic Islands           69908.04            53001.88
4 2014-04-01    Basque Country          158685.76           143567.15

   gasoline_consumption  diesel  gasoline  diesel_withouttaxes  \
0              57971.26     NaN       NaN                  NaN
1              11162.77     NaN       NaN                  NaN
2               7699.68     NaN       NaN                  NaN
3              16906.16     NaN       NaN                  NaN
4              15118.61     NaN       NaN                  NaN

   gasoline_withoutaxes lastbrentprice  apparent_temperature_max  \
0                   NaN         108,07                     24.56
1                   NaN         108,07                     19.90
2                   NaN         108,07                     15.34
3                   NaN         108,07                     20.76
4                   NaN         108,07                     14.32

   days_holidays  total_gasoline_total  total_diesel_total  UnemRate  IPC
0            2.0              176507.0            262207.0     34.74  0.3
1            3.0               27733.0             39691.0     20.83  0.1
2            2.0               21355.0             32798.0     21.02  0.2
3            2.0               46543.0             29217.0     19.04  0.6
4            3.0               43902.0             62401.0     16.13  0.6

In [ ]:
merged_final.head(100)

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,total_gasoline_total,total_diesel_total,UnemRate,IPC
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0,34.74,0.3
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0,20.83,0.1
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0,21.02,0.2
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0,19.04,0.6
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0,16.13,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2014-07-01,Andalusia,438204.60,373922.04,64282.56,NaN,NaN,NaN,NaN,"106,02",34.33,NaN,176507.0,262207.0,35.21,-0.6
96,2014-07-01,Aragon,121851.51,109073.06,12778.45,NaN,NaN,NaN,NaN,"106,02",28.40,NaN,27733.0,39691.0,18.36,-0.4
97,2014-07-01,Asturias,64704.91,56027.25,8677.66,NaN,NaN,NaN,NaN,"106,02",22.44,NaN,21355.0,32798.0,19.96,-0.5
98,2014-07-01,Balearic Islands,84949.07,62056.32,22892.75,NaN,NaN,NaN,NaN,"106,02",30.95,NaN,46543.0,29217.0,15.94,0.1
99,2014-07-01,Basque Country,166676.90,149900.91,16775.99,NaN,NaN,NaN,NaN,"106,02",22.48,NaN,43902.0,62401.0,15.21,-0.1

In [ ]:
merged_final.rename(columns={'total_gasoline_total': 'gasoline_fleet'}, inplace=True)
merged_final.rename(columns={'total_diesel_total': 'diesel_fleet'}, inplace=True)

In [ ]:
merged_final.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0,34.74,0.3
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0,20.83,0.1
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0,21.02,0.2
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0,19.04,0.6
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0,16.13,0.6

In [ ]:
merged_final.tail()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC
2313,2024-01-01,Madrid,276509.83,213020.33,63489.50,117.262,108.874,70.3572,65.3244,"80,55",9.74,NaN,NaN,NaN,9.19,2.7
2314,2024-01-01,Melilla,3496.48,2949.54,546.94,117.262,108.874,70.3572,65.3244,"80,55",NaN,NaN,NaN,NaN,32.44,3.5
2315,2024-01-01,Murcia,107168.80,94401.81,12766.99,117.262,108.874,70.3572,65.3244,"80,55",17.09,NaN,NaN,NaN,12.95,3.6
2316,2024-01-01,Navarre,66694.34,60395.44,6298.90,117.262,108.874,70.3572,65.3244,"80,55",8.50,NaN,NaN,NaN,NaN,NaN
2317,2024-01-01,Valencian Region,235434.91,183371.12,52063.79,117.262,108.874,70.3572,65.3244,"80,55",15.16,NaN,NaN,NaN,13.44,3.6

In [ ]:
merged_final['region'].unique()

array(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands',
       'Basque Country', 'Canary Islands', 'Cantabria',
       'Castile and Le√≥n', 'Castile-La Mancha', 'Catalonia', 'Ceuta',
       'Extremadura', 'Galicia', 'La Rioja', 'Madrid', 'Melilla',
       'Murcia', 'Navarre', 'Valencian Region'], dtype=object)

In [ ]:
# Drive Folder
#csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_UnemRate_IPC.csv'

# csv file for oilconsumption CCAA
#merged_final.to_csv(csv_file_path, index=False)

#print(f'DataFrame saved successfully to {csv_file_path}')

# Import GDP Dataset

In [ ]:
# Sharedrive file

file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /Macroeconomic Data/gdp_data_final.xlsx'

# second sheet to be uploaded
df_gdp = pd.read_excel(file_path)

In [ ]:
df_gdp.head(50)

    year_month             region           gdp    population  gdp_xcapita
0   2014-01-01          Andalusia  1.144824e+07  8.381267e+06  1365.932260
1   2014-01-01   Balearic Islands  2.225730e+06  1.106336e+06  2011.802144
2   2014-01-01            Galicia  4.502699e+06  2.747907e+06  1638.592295
3   2014-01-01  Castile-La Mancha  2.938191e+06  2.077525e+06  1414.274526
4   2014-01-01           Asturias  1.716660e+06  1.059906e+06  1619.634267
5   2014-01-01          Catalonia  1.623530e+07  7.440655e+06  2181.972291
6   2014-01-01            Navarre  1.454235e+06  6.372150e+05  2282.172651
7   2014-01-01          Cantabria  1.002366e+06  5.877970e+05  1705.292610
8   2014-01-01           La Rioja  6.386617e+05  3.162320e+05  2019.598444
9   2014-01-01             Aragon  2.683205e+06  1.331792e+06  2014.732363
10  2014-01-01     Basque Country  5.208021e+06  2.173092e+06  2396.595078
11  2014-01-01             Murcia  2.219798e+06  1.462446e+06  1517.866655
12  2014-01-01   Castile and Le√≥n  4.283141e+06  2.497297e+06  1715.110637
13  2014-01-01        Extremadura  1.414997e+06  1.097298e+06  1289.528897
14  2014-01-01     Canary Islands  3.263669e+06  2.097508e+06  1555.974639
15  2014-01-01             Madrid  1.614141e+07  6.377936e+06  2530.819929
16  2014-01-01   Valencian Region  8.006332e+06  4.963466e+06  1613.052836
17  2014-02-01     Basque Country  5.347753e+06  2.172669e+06  2461.374696
18  2014-02-01          Catalonia  1.667090e+07  7.436744e+06  2241.693457
19  2014-02-01  Castile-La Mancha  3.017024e+06  2.076143e+06  1453.187021
20  2014-02-01           Asturias  1.762719e+06  1.059233e+06  1664.146138
21  2014-02-01     Canary Islands  3.351234e+06  2.097831e+06  1597.475330
22  2014-02-01             Aragon  2.755196e+06  1.331253e+06  2069.626798
23  2014-02-01   Valencian Region  8.221144e+06  4.961839e+06  1656.874348
24  2014-02-01             Murcia  2.279356e+06  1.462590e+06  1558.437954
25  2014-02-01          Cantabria  1.029260e+06  5.876440e+05  1751.501952
26  2014-02-01            Navarre  1.493252e+06  6.371570e+05  2343.617245
27  2014-02-01   Balearic Islands  2.285447e+06  1.106477e+06  2065.517309
28  2014-02-01           La Rioja  6.557971e+05  3.159840e+05  2075.412396
29  2014-02-01        Extremadura  1.452962e+06  1.097003e+06  1324.483364
30  2014-02-01             Madrid  1.657448e+07  6.375244e+06  2599.819535
31  2014-02-01          Andalusia  1.175540e+07  8.381253e+06  1402.582914
32  2014-02-01   Castile and Le√≥n  4.398059e+06  2.495451e+06  1762.430751
33  2014-02-01            Galicia  4.623508e+06  2.746862e+06  1683.196247
34  2014-03-01          Andalusia  1.079752e+07  8.381239e+06  1288.296817
35  2014-03-01   Valencian Region  7.551252e+06  4.960213e+06  1522.364365
36  2014-03-01           La Rioja  6.023601e+05  3.157360e+05  1907.796555
37  2014-03-01  Castile-La Mancha  2.771184e+06  2.074760e+06  1335.664864
38  2014-03-01          Cantabria  9.453913e+05  5.874910e+05  1609.201312
39  2014-03-01   Castile and Le√≥n  4.039687e+06  2.493604e+06  1620.019450
40  2014-03-01        Extremadura  1.334569e+06  1.096708e+06  1216.886227
41  2014-03-01            Navarre  1.371576e+06  6.370990e+05  2152.845603
42  2014-03-01             Madrid  1.522393e+07  6.372553e+06  2388.984019
43  2014-03-01             Murcia  2.093624e+06  1.462734e+06  1431.309072
44  2014-03-01   Balearic Islands  2.099219e+06  1.106617e+06  1896.969836
45  2014-03-01             Aragon  2.530691e+06  1.330713e+06  1901.755997
46  2014-03-01            Galicia  4.246765e+06  2.745817e+06  1546.630855
47  2014-03-01     Basque Country  4.911996e+06  2.172247e+06  2261.251271
48  2014-03-01     Canary Islands  3.078161e+06  2.098155e+06  1467.080091
49  2014-03-01          Catalonia  1.531249e+07  7.432833e+06  2060.114434

In [ ]:
df_gdp['region'].unique()

array(['Andalusia', 'Balearic Islands', 'Galicia', 'Castile-La Mancha',
       'Asturias', 'Catalonia', 'Navarre', 'Cantabria', 'La Rioja',
       'Aragon', 'Basque Country', 'Murcia', 'Castile and Le√≥n',
       'Extremadura', 'Canary Islands', 'Madrid', 'Valencian Region'],
      dtype=object)

In [ ]:
print(df_gdp.columns)
print(merged_final.columns)

Index(['year_month', 'region', 'gdp', 'population', 'gdp_xcapita'], dtype='object')
Index(['year_month', 'region', 'total_consumption', 'diesel_consumption',
       'gasoline_consumption', 'diesel', 'gasoline', 'diesel_withouttaxes',
       'gasoline_withoutaxes', 'lastbrentprice', 'apparent_temperature_max',
       'days_holidays', 'gasoline_fleet', 'diesel_fleet', 'UnemRate', 'IPC'],
      dtype='object')

In [ ]:
standardization_map = {
    # Regiones ya mapeadas
    'Andalucia': 'Andalusia',
    'Andaluc√≠a': 'Andalusia',
    'Arag√≥n': 'Aragon',
    'Aragon': 'Aragon',
    'Asturias': 'Asturias',
    'Asturias (Principado de)': 'Asturias',
    'Balearic Islands': 'Balearic Islands',
    'BalearicIslands': 'Balearic Islands',
    'Balears (Illes)': 'Balearic Islands',
    'Basque Country': 'Basque Country',
    'BasqueCountry': 'Basque Country',
    'Pa√≠s Vasco': 'Basque Country',
    'Canarias': 'Canary Islands',
    'Canary Islands': 'Canary Islands',
    'CanaryIslands': 'Canary Islands',
    'Castile and Le√≥n': 'Castile and Le√≥n',
    'CastileandLe√≥n': 'Castile and Le√≥n',
    'Castilla y Leon': 'Castile and Le√≥n',
    'Castile-La Mancha': 'Castile-La Mancha',
    'CastileLaMancha': 'Castile-La Mancha',
    'Castilla-La Mancha': 'Castile-La Mancha',
    'Catalu√±a': 'Catalonia',
    'Madrid (Comunidad de)': 'Madrid',
    'Madrid': 'Madrid',
    'La Rioja': 'La Rioja',
    'Rioja (La)': 'La Rioja',
    'Rioja': 'La Rioja',
    'Navarra': 'Navarre',
    'Navarra (Comunidad Foral de)': 'Navarre',
    'Comunitat Valenciana': 'Valencian Region',
    'ValencianCommunity': 'Valencian Region',
    'Valencia': 'Valencian Region',
    'Murcia': 'Murcia',
    'Murcia (Regi√≥n de)': 'Murcia',
    'Andalusia': 'Andalusia',
    'Castile-La Mancha': 'Castilla-La Mancha',
    'Valencian Region': 'Valencian Region',
    'Navarre': 'Navarre',
    'Catalonia': 'Catalonia',
    'Extremadura': 'Extremadura',
    'Cantabria': 'Cantabria',
    'Galicia': 'Galicia',
    'Castile and Leon': 'Castile and Leon',
    # Nuevas regiones a a√±adir
    'Asturias, Principado de': 'Asturias',
    'Balears, Illes': 'Balearic Islands',
    'Castilla y Le√≥n': 'Castile and Le√≥n',
    'Castilla - La Mancha': 'Castile-La Mancha',
    'Madrid, Comunidad de': 'Madrid',
    'Murcia, Regi√≥n de': 'Murcia',
    'Navarra, Comunidad Foral de': 'Navarre',
    'Rioja, La': 'La Rioja',
    'Ceuta': 'Ceuta',
    'Melilla': 'Melilla'
}

# Apply the standardization map to df_gdp
df_gdp['region_standardized'] = df_gdp['region'].map(standardization_map)

# Verify the new column exists and has the correct values
print(df_gdp[['region', 'region_standardized']].head())

# Check for missing values in the standardized region column
missing_standardized = df_gdp[df_gdp['region_standardized'].isna()]
print(f"Missing standardized regions:\n{missing_standardized}")

# Check for unexpected standardized region names
unique_standardized = df_gdp['region_standardized'].unique()
print(f"Unique standardized region names:\n{unique_standardized}")

              region region_standardized
0          Andalusia           Andalusia
1   Balearic Islands    Balearic Islands
2            Galicia             Galicia
3  Castile-La Mancha  Castilla-La Mancha
4           Asturias            Asturias
Missing standardized regions:
Empty DataFrame
Columns: [year_month, region, gdp, population, gdp_xcapita, region_standardized]
Index: []
Unique standardized region names:
['Andalusia' 'Balearic Islands' 'Galicia' 'Castilla-La Mancha' 'Asturias'
 'Catalonia' 'Navarre' 'Cantabria' 'La Rioja' 'Aragon' 'Basque Country'
 'Murcia' 'Castile and Le√≥n' 'Extremadura' 'Canary Islands' 'Madrid'
 'Valencian Region']

In [ ]:
df_gdp['year_month'] = pd.to_datetime(df_gdp['year_month'])

In [ ]:
# Identify missing dates
missing_dates_in_final = merged_final[~merged_final['year_month'].isin(df_gdp['year_month'])]['year_month'].unique()
missing_dates_in_gdp = df_gdp[~df_gdp['year_month'].isin(merged_final['year_month'])]['year_month'].unique()

In [ ]:
print("Dates in merged_final not in df_gdp:")
print(missing_dates_in_gdp)

print("\nDates in df_gdp not in merged_final:")
print(missing_dates_in_final)

Dates in merged_final not in df_gdp:
<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]

Dates in df_gdp not in merged_final:
<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]

In [ ]:

# Convert merged_final['year_month'] to datetime format (if not already)
merged_final['year_month'] = pd.to_datetime(merged_final['year_month'])

# Ensure df_gdp['year_month'] represents the first day of each month
df_gdp['year_month'] = pd.to_datetime(df_gdp['year_month']).dt.to_period('M').dt.to_timestamp()

# Apply the updated standardization map to the GDP dataset
df_gdp['region_standardized'] = df_gdp['region'].map(standardization_map)
merged_final['region_standardized'] = merged_final['region'].map(standardization_map)

# Identify missing dates
missing_dates_in_gdp = merged_final[~merged_final['year_month'].isin(df_gdp['year_month'])]['year_month'].unique()
missing_dates_in_weather = df_gdp[~df_gdp['year_month'].isin(merged_final['year_month'])]['year_month'].unique()

print("Dates in merged_final not in df_gdp:")
print(missing_dates_in_gdp)

print("\nDates in df_gdp not in merged_final:")
print(missing_dates_in_weather)

# Merge the datasets using standardized region names and year_month
merged_final2 = pd.merge(merged_final,
                         df_gdp[['year_month', 'region_standardized', 'gdp', 'population', 'gdp_xcapita']],
                         left_on=['year_month', 'region_standardized'],
                         right_on=['year_month', 'region_standardized'],
                         how='left')

Dates in merged_final not in df_gdp:
<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]

Dates in df_gdp not in merged_final:
<DatetimeArray>
[]
Length: 0, dtype: datetime64[ns]

In [ ]:

merged_final2.head(100)

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,region_standardized,gdp,population,gdp_xcapita
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0,34.74,0.3,Andalusia,1.141329e+07,8.381274e+06,1361.761038
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0,20.83,0.1,Aragon,2.675013e+06,1.330196e+06,2010.992492
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0,21.02,0.2,Asturias,1.711419e+06,1.057723e+06,1618.022155
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0,19.04,0.6,Balearic Islands,2.218935e+06,1.106940e+06,2004.565883
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0,16.13,0.6,Basque Country,5.192121e+06,2.172151e+06,2390.313521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2014-07-01,Andalusia,438204.60,373922.04,64282.56,NaN,NaN,NaN,NaN,"106,02",34.33,NaN,176507.0,262207.0,35.21,-0.6,Andalusia,1.175074e+07,8.381379e+06,1402.005997
96,2014-07-01,Aragon,121851.51,109073.06,12778.45,NaN,NaN,NaN,NaN,"106,02",28.40,NaN,27733.0,39691.0,18.36,-0.4,Aragon,2.754104e+06,1.328644e+06,2072.868955
97,2014-07-01,Asturias,64704.91,56027.25,8677.66,NaN,NaN,NaN,NaN,"106,02",22.44,NaN,21355.0,32798.0,19.96,-0.5,Asturias,1.762020e+06,1.055212e+06,1669.825472
98,2014-07-01,Balearic Islands,84949.07,62056.32,22892.75,NaN,NaN,NaN,NaN,"106,02",30.95,NaN,46543.0,29217.0,15.94,0.1,Balearic Islands,2.284541e+06,1.107910e+06,2062.026891
99,2014-07-01,Basque Country,166676.90,149900.91,16775.99,NaN,NaN,NaN,NaN,"106,02",22.48,NaN,43902.0,62401.0,15.21,-0.1,Basque Country,5.345634e+06,2.171862e+06,2461.314130

In [ ]:
merged_final2.tail()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,region_standardized,gdp,population,gdp_xcapita
2313,2024-01-01,Madrid,276509.83,213020.33,63489.50,117.262,108.874,70.3572,65.3244,"80,55",9.74,NaN,NaN,NaN,9.19,2.7,Madrid,1.686793e+07,6871903.0,2454.622542
2314,2024-01-01,Melilla,3496.48,2949.54,546.94,117.262,108.874,70.3572,65.3244,"80,55",NaN,NaN,NaN,NaN,32.44,3.5,Melilla,NaN,NaN,NaN
2315,2024-01-01,Murcia,107168.80,94401.81,12766.99,117.262,108.874,70.3572,65.3244,"80,55",17.09,NaN,NaN,NaN,12.95,3.6,Murcia,2.307995e+06,1551692.0,1487.405661
2316,2024-01-01,Navarre,66694.34,60395.44,6298.90,117.262,108.874,70.3572,65.3244,"80,55",8.50,NaN,NaN,NaN,NaN,NaN,Navarre,1.456309e+06,672155.0,2166.626973
2317,2024-01-01,Valencian Region,235434.91,183371.12,52063.79,117.262,108.874,70.3572,65.3244,"80,55",15.16,NaN,NaN,NaN,13.44,3.6,Valencian Region,8.147782e+06,5216195.0,1562.016334

In [ ]:
# Eliminar la columna temporal 'region_standardized' si ya no es necesaria
merged_final2.drop(columns=['region_standardized'], inplace=True)

In [ ]:
merged_final2.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0,34.74,0.3,1.141329e+07,8.381274e+06,1361.761038
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0,20.83,0.1,2.675013e+06,1.330196e+06,2010.992492
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0,21.02,0.2,1.711419e+06,1.057723e+06,1618.022155
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0,19.04,0.6,2.218935e+06,1.106940e+06,2004.565883
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0,16.13,0.6,5.192121e+06,2.172151e+06,2390.313521

In [ ]:
merged_final2.tail()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita
2313,2024-01-01,Madrid,276509.83,213020.33,63489.50,117.262,108.874,70.3572,65.3244,"80,55",9.74,NaN,NaN,NaN,9.19,2.7,1.686793e+07,6871903.0,2454.622542
2314,2024-01-01,Melilla,3496.48,2949.54,546.94,117.262,108.874,70.3572,65.3244,"80,55",NaN,NaN,NaN,NaN,32.44,3.5,NaN,NaN,NaN
2315,2024-01-01,Murcia,107168.80,94401.81,12766.99,117.262,108.874,70.3572,65.3244,"80,55",17.09,NaN,NaN,NaN,12.95,3.6,2.307995e+06,1551692.0,1487.405661
2316,2024-01-01,Navarre,66694.34,60395.44,6298.90,117.262,108.874,70.3572,65.3244,"80,55",8.50,NaN,NaN,NaN,NaN,NaN,1.456309e+06,672155.0,2166.626973
2317,2024-01-01,Valencian Region,235434.91,183371.12,52063.79,117.262,108.874,70.3572,65.3244,"80,55",15.16,NaN,NaN,NaN,13.44,3.6,8.147782e+06,5216195.0,1562.016334

In [ ]:
# Drive Folder
#csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp.csv'

# csv file for oilconsumption CCAA
#merged_final2.to_csv(csv_file_path, index=False)

#print(f'DataFrame saved successfully to {csv_file_path}')

# COVID AND RUSSIAN UKRAINE WAR

COVID-19 Pandemic in Spain:

The COVID-19 pandemic started affecting Spain significantly around early 2020. The first confirmed case was reported in late January 2020, and by March 2020, Spain had implemented lockdown measures and declared a state of emergency.
Start Date: You can consider early 2020, around February or March, as the start date for the impact of COVID-19 on Spain.
End Date: The end date can be more subjective, depending on when the situation began to normalize or when significant milestones like vaccination campaigns started impacting daily life. A reasonable end date could be mid-2021 or later, but this can vary based on your analysis needs.




The Russian military intervention in Ukraine began on February 24, 2022, when Russian President Vladimir Putin announced a special military operation in Ukraine. This marked a significant escalation of the conflict that had been ongoing since 2014, when Russia annexed Crimea and a separatist insurgency began in eastern Ukraine.

The 2022 invasion resulted in widespread condemnation internationally and led to severe humanitarian and economic consequences for Ukraine and the broader region. The conflict has had far-reaching impacts, including geopolitical tensions, economic sanctions on Russia, and disruptions in various sectors, including energy markets and fuel consumption patterns across Europe and beyond.

In [ ]:
#  start and end dates for COVID-19 and Ukraine war
covid_start_date = pd.to_datetime('2020-03-01')
covid_end_date = pd.to_datetime('2021-06-01')

ukraine_war_start_date = pd.to_datetime('2022-02-01')
ukraine_war_end_date = pd.to_datetime('2024-01-01')  #data set end date

#  periods related to COVID-19 and Ukraine war
merged_final2['covid_period'] = merged_final2['year_month'].apply(lambda x: 1 if covid_start_date <= x <= covid_end_date else 0)
merged_final2['ukraine_war_period'] = merged_final2['year_month'].apply(lambda x: 1 if ukraine_war_start_date <= x <= ukraine_war_end_date else 0)

In [ ]:
merged_final2.tail()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period
2313,2024-01-01,Madrid,276509.83,213020.33,63489.50,117.262,108.874,70.3572,65.3244,"80,55",9.74,NaN,NaN,NaN,9.19,2.7,1.686793e+07,6871903.0,2454.622542,0,1
2314,2024-01-01,Melilla,3496.48,2949.54,546.94,117.262,108.874,70.3572,65.3244,"80,55",NaN,NaN,NaN,NaN,32.44,3.5,NaN,NaN,NaN,0,1
2315,2024-01-01,Murcia,107168.80,94401.81,12766.99,117.262,108.874,70.3572,65.3244,"80,55",17.09,NaN,NaN,NaN,12.95,3.6,2.307995e+06,1551692.0,1487.405661,0,1
2316,2024-01-01,Navarre,66694.34,60395.44,6298.90,117.262,108.874,70.3572,65.3244,"80,55",8.50,NaN,NaN,NaN,NaN,NaN,1.456309e+06,672155.0,2166.626973,0,1
2317,2024-01-01,Valencian Region,235434.91,183371.12,52063.79,117.262,108.874,70.3572,65.3244,"80,55",15.16,NaN,NaN,NaN,13.44,3.6,8.147782e+06,5216195.0,1562.016334,0,1

In [ ]:
# Drive Folder
#csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp_covid_ukrainewar.csv'

# csv file for oilconsumption CCAA
#merged_final2.to_csv(csv_file_path, index=False)

#print(f'DataFrame saved successfully to {csv_file_path}')

# CPI Hotels, Transport & Tourism

In [ ]:
# Sharedrive file

file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/cpi_housing_transport_tourism.csv'

# second sheet to be uploaded
df_cpi = pd.read_csv(file_path)

In [ ]:
df_cpi.head()

   year_month                   region  housing  transport  tourism
0  2024-05-01                Andaluc√≠a      1.1       -0.6      0.6
1  2024-05-01                   Arag√≥n      0.7       -0.9      1.1
2  2024-05-01  Asturias, Principado de      0.7       -0.8      0.2
3  2024-05-01           Balears, Illes      1.1       -0.4      2.1
4  2024-05-01                 Canarias      0.9        0.2     -0.2

In [ ]:
# Convert year_month to datetime in both datasets
merged_final2['year_month'] = pd.to_datetime(merged_final2['year_month'])
df_cpi['year_month'] = pd.to_datetime(df_cpi['year_month'])

# Filter df_gdp to match the date range of merged_final
df_cpi = df_cpi[df_cpi['year_month'].isin(merged_final2['year_month'])]

# Apply the updated standardization map to the GDP dataset
df_cpi['region_standardized'] = df_cpi['region'].map(standardization_map)
merged_final2['region_standardized'] = merged_final2['region'].map(standardization_map)

# Filter merged_final to match the date range of df_gdp
merged_final2 = merged_final2[merged_final2['year_month'].isin(df_cpi['year_month'])]

# Verify that the regions are standardized and matching
unique_regions_merged = merged_final2['region'].unique()
unique_regions_gdp = df_cpi['region_standardized'].unique()

print(f"Unique regions in merged_final: {unique_regions_merged}")
print(f"Unique regions in df_gdp: {unique_regions_gdp}")

# Merge the datasets on year_month and standardized region
merged_final2 = pd.merge(
    merged_final2,
    df_cpi[['year_month', 'region_standardized', 'housing', 'transport', 'tourism']],
    left_on=['year_month', 'region'],
    right_on=['year_month', 'region_standardized'],
    how='left'
)

Unique regions in merged_final: ['Andalusia' 'Aragon' 'Asturias' 'Balearic Islands' 'Basque Country'
 'Canary Islands' 'Cantabria' 'Castile and Le√≥n' 'Castile-La Mancha'
 'Catalonia' 'Ceuta' 'Extremadura' 'Galicia' 'La Rioja' 'Madrid' 'Melilla'
 'Murcia' 'Navarre' 'Valencian Region']
Unique regions in df_gdp: ['Andalusia' 'Aragon' 'Asturias' 'Balearic Islands' 'Canary Islands'
 'Cantabria' 'Castile and Le√≥n' 'Castile-La Mancha' 'Catalonia'
 'Valencian Region' 'Extremadura' 'Galicia' 'Madrid' 'Murcia' 'Navarre'
 'Basque Country' 'La Rioja' 'Ceuta' 'Melilla']

In [ ]:
# Eliminar la columna temporal 'region_standardized' si ya no es necesaria
merged_final2.drop(columns=['region_standardized_x','region_standardized_y'], inplace=True)

In [ ]:
merged_final2.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel,gasoline,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,housing,transport,tourism
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0,34.74,0.3,1.141329e+07,8.381274e+06,1361.761038,0,0,0.0,0.4,0.9
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0,20.83,0.1,2.675013e+06,1.330196e+06,2010.992492,0,0,-0.2,0.4,1.0
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0,21.02,0.2,1.711419e+06,1.057723e+06,1618.022155,0,0,0.1,0.7,0.5
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0,19.04,0.6,2.218935e+06,1.106940e+06,2004.565883,0,0,-0.1,0.4,0.4
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0,16.13,0.6,5.192121e+06,2.172151e+06,2390.313521,0,0,-0.1,0.5,0.7

# IPI DATASET

In [ ]:
# Sharedrive file

file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /Macroeconomic Data/IPI_Processed.xlsx'

# second sheet to be uploaded
df_ipi = pd.read_excel(file_path)

In [ ]:
df_ipi.head()

  year_month     region     ipi
0 2024-04-01  Andalusia  98.372
1 2024-03-01  Andalusia  94.188
2 2024-02-01  Andalusia  93.454
3 2024-01-01  Andalusia  96.894
4 2023-12-01  Andalusia  87.902

In [ ]:
#drop Ceuta & Melilla
df_ipi = df_ipi[~df_ipi['region'].isin(['Melilla', 'Ceuta'])]

In [ ]:
# Convert year_month to datetime in both datasets
merged_final2['year_month'] = pd.to_datetime(merged_final2['year_month'])
df_ipi['year_month'] = pd.to_datetime(df_ipi['year_month'])

# Filter df_gdp to match the date range of merged_final
df_ipi = df_ipi[df_ipi['year_month'].isin(merged_final2['year_month'])]

# Apply the updated standardization map to the GDP dataset
df_ipi['region_standardized'] = df_ipi['region'].map(standardization_map)
merged_final2['region_standardized'] = merged_final2['region'].map(standardization_map)

# Filter merged_final to match the date range of df_gdp
merged_final3 = merged_final2[merged_final2['year_month'].isin(df_ipi['year_month'])]

# Verify that the regions are standardized and matching
unique_regions_merged = merged_final3['region'].unique()
unique_regions_gdp = df_ipi['region_standardized'].unique()

print(f"Unique regions in merged_final3: {unique_regions_merged}")
print(f"Unique regions in df_ipi: {unique_regions_gdp}")

# Merge the datasets on year_month and standardized region
merged_final3 = pd.merge(
    merged_final3,
    df_ipi[['year_month', 'region_standardized', 'ipi']],
    left_on=['year_month', 'region'],
    right_on=['year_month', 'region_standardized'],
    how='left'
)

Unique regions in merged_final3: ['Andalusia' 'Aragon' 'Asturias' 'Balearic Islands' 'Basque Country'
 'Canary Islands' 'Cantabria' 'Castile and Le√≥n' 'Castile-La Mancha'
 'Catalonia' 'Ceuta' 'Extremadura' 'Galicia' 'La Rioja' 'Madrid' 'Melilla'
 'Murcia' 'Navarre' 'Valencian Region']
Unique regions in df_ipi: ['Andalusia' 'Aragon' 'Asturias' 'Balearic Islands' 'Canary Islands'
 'Cantabria' 'Castile and Le√≥n' 'Castilla-La Mancha' 'Catalonia'
 'Valencian Region' 'Extremadura' 'Galicia' 'Madrid' 'Murcia' 'Navarre'
 'Basque Country' 'La Rioja']

In [ ]:
# Renombrar las columnas
merged_final3 = merged_final3.rename(columns={
    'housing': 'ipc_housing',
    'transport': 'ipc_transport',
    'tourism': 'ipc_tourism',
    'diesel':'diesel_price',
    'gasoline':'gasoline_price'
})

In [ ]:
# Eliminar la columna temporal 'region_standardized' si ya no es necesaria
merged_final3.drop(columns=['region_standardized'], inplace=True)

KeyError: "['region_standardized'] not found in axis"

In [ ]:
merged_final3.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,region_standardized_x,region_standardized_y,ipi
0,2014-04-01,Andalusia,386716.46,328745.20,57971.26,NaN,NaN,NaN,NaN,"108,07",24.56,2.0,176507.0,262207.0,34.74,0.3,1.141329e+07,8.381274e+06,1361.761038,0,0,0.0,0.4,0.9,Andalusia,Andalusia,94.041
1,2014-04-01,Aragon,109520.43,98357.66,11162.77,NaN,NaN,NaN,NaN,"108,07",19.90,3.0,27733.0,39691.0,20.83,0.1,2.675013e+06,1.330196e+06,2010.992492,0,0,-0.2,0.4,1.0,Aragon,Aragon,94.676
2,2014-04-01,Asturias,58483.64,50783.96,7699.68,NaN,NaN,NaN,NaN,"108,07",15.34,2.0,21355.0,32798.0,21.02,0.2,1.711419e+06,1.057723e+06,1618.022155,0,0,0.1,0.7,0.5,Asturias,Asturias,85.994
3,2014-04-01,Balearic Islands,69908.04,53001.88,16906.16,NaN,NaN,NaN,NaN,"108,07",20.76,2.0,46543.0,29217.0,19.04,0.6,2.218935e+06,1.106940e+06,2004.565883,0,0,-0.1,0.4,0.4,Balearic Islands,Balearic Islands,114.364
4,2014-04-01,Basque Country,158685.76,143567.15,15118.61,NaN,NaN,NaN,NaN,"108,07",14.32,3.0,43902.0,62401.0,16.13,0.6,5.192121e+06,2.172151e+06,2390.313521,0,0,-0.1,0.5,0.7,Basque Country,Basque Country,88.827

# YEAR_MONTH AS INDEX

In [ ]:

# Convert the 'year_month' column to datetime format
merged_final3['year_month'] = pd.to_datetime(merged_final3['year_month'])

# Set 'year_month' as the index
merged_final3.set_index('year_month', inplace=True)

# Sort the DataFrame by the index
merged_final3.sort_index(inplace=True)

In [ ]:
merged_final3.head()

,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,region_standardized_x,region_standardized_y,ipi
year_month,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,Valencian Region,Valencian Region,81.650
2014-01-01,Melilla,6512.30,6022.72,489.58,NaN,NaN,NaN,NaN,"106,40",NaN,NaN,NaN,NaN,24.43,-0.2,NaN,NaN,NaN,0,0,0.4,-0.8,0.1,Melilla,NaN,NaN
2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,Madrid,Madrid,89.055
2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,La Rioja,La Rioja,110.747
2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,Galicia,Galicia,94.645

In [ ]:

# Drop the rows where 'region' is either 'Melilla' or 'Ceuta'
merged_final3 = merged_final3[~merged_final3['region'].isin(['Melilla', 'Ceuta'])]

In [ ]:
merged_final3.head(20)

,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,region_standardized_x,region_standardized_y,ipi
year_month,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,Valencian Region,Valencian Region,81.650
2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,Madrid,Madrid,89.055
2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,La Rioja,La Rioja,110.747
2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,Galicia,Galicia,94.645
2014-01-01,Extremadura,64147.55,56911.49,7236.06,NaN,NaN,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,Extremadura,Extremadura,76.387
2014-01-01,Castile-La Mancha,189436.62,176463.41,12973.21,NaN,NaN,NaN,NaN,"106,40",8.27,2.0,38917.0,78301.0,NaN,NaN,2.938191e+06,2.077525e+06,1414.274526,0,0,0.6,-0.6,-0.1,Castilla-La Mancha,NaN,NaN
2014-01-01,Castile and Le√≥n,216672.35,198677.80,17994.55,NaN,NaN,NaN,NaN,"106,40",5.99,NaN,NaN,NaN,NaN,NaN,4.283141e+06,2.497297e+06,1715.110637,0,0,0.3,-0.5,-0.3,Castile and Le√≥n,Castile and Le√≥n,105.204
2014-01-01,Cantabria,33733.84,29437.72,4296.12,NaN,NaN,NaN,NaN,"106,40",10.37,2.0,12717.0,19594.0,20.95,0.3,1.002366e+06,5.877970e+05,1705.292610,0,0,0.2,-1.7,-0.2,Cantabria,Cantabria,88.667
2014-01-01,Canary Islands,223980.33,183320.11,40660.22,NaN,NaN,NaN,NaN,"106,40",17.38,2.0,82666.0,41308.0,32.55,-0.2,3.263669e+06,2.097508e+06,1555.974639,0,0,0.3,-0.2,0.0,Canary Islands,Canary Islands,109.046
2014-01-01,Basque Country,166031.14,152259.32,13771.82,NaN,NaN,NaN,NaN,"106,40",10.38,2.0,43902.0,62401.0,17.36,0.6,5.208021e+06,2.173092e+06,2396.595078,0,0,0.9,-0.5,0.0,Basque Country,Basque Country,89.975
2014-01-01,Balearic Islands,64647.68,52277.66,12370.02,NaN,NaN,NaN,NaN,"106,40",12.39,2.0,46543.0,29217.0,26.70,0.5,2.225730e+06,1.106336e+06,2011.802144,0,0,0.4,-0.4,0.0,Balearic Islands,Balearic Islands,107.469
2014-01-01,Asturias,61196.32,54565.86,6630.46,NaN,NaN,NaN,NaN,"106,40",8.67,2.0,21355.0,32798.0,22.75,0.0,1.716660e+06,1.059906e+06,1619.634267,0,0,0.4,-0.6,-0.4,Asturias,Asturias,89.240
2014-01-01,Aragon,121972.03,112517.91,9454.12,NaN,NaN,NaN,NaN,"106,40",9.34,2.0,27733.0,39691.0,22.85,0.0,2.683205e+06,1.331792e+06,2014.732363,0,0,0.3,-0.5,-0.2,Aragon,Aragon,91.330
2014-01-01,Andalusia,377814.73,324160.87,53653.86,NaN,NaN,NaN,NaN,"106,40",13.67,2.0,176507.0,262207.0,34.94,0.1,1.144824e+07,8.381267e+06,1365.932260,0,0,0.5,-0.5,-0.5,Andalusia,Andalusia,105.607
2014-01-01,Murcia,92575.18,83860.29,8714.89,NaN,NaN,NaN,NaN,"106,40",14.27,2.0,29655.0,50107.0,27.71,0.2,2.219798e+06,1.462446e+06,1517.866655,0,0,0.5,-0.5,-0.1,Murcia,Murcia,76.991
2014-01-01,Navarre,69090.03,64039.61,5050.42,NaN,NaN,NaN,NaN,"106,40",6.52,2.0,13001.0,22240.0,NaN,NaN,1.454235e+06,6.372150e+05,2282.172651,0,0,0.4,-1.0,-0.3,Navarre,Navarre,89.109
2014-01-01,Catalonia,390505.34,333824.18,56681.16,NaN,NaN,NaN,NaN,"106,40",12.43,2.0,205398.0,202067.0,22.10,0.3,1.623530e+07,7.440655e+06,2181.972291,0,0,0.7,-0.4,-0.3,Catalonia,Catalonia,91.870
2014-02-01,Andalusia,347637.16,298274.45,49362.71,NaN,NaN,NaN,NaN,"109,07",13.45,1.0,176507.0,262207.0,34.94,-0.2,1.175540e+07,8.381253e+06,1402.582914,0,0,0.2,0.0,0.2,Andalusia,Andalusia,95.693
2014-02-01,Murcia,84484.15,76193.39,8290.76,NaN,NaN,NaN,NaN,"109,07",15.27,NaN,29655.0,50107.0,27.71,-0.1,2.279356e+06,1.462590e+06,1558.437954,0,0,0.0,0.0,0.1,Murcia,Murcia,78.461
2014-02-01,Madrid,266725.19,225359.26,41365.93,NaN,NaN,NaN,NaN,"109,07",6.30,NaN,143123.0,206366.0,20.43,-0.1,1.657448e+07,6.375244e+06,2599.819535,0,0,0.1,-0.2,0.1,Madrid,Madrid,89.216

In [ ]:
# Drive Folder
#csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp_covid_ukrainewar_cpi_ipi.csv'

# csv file for oilconsumption CCAA
#merged_final3.to_csv(csv_file_path, index=True)

#print(f'DataFrame saved successfully to {csv_file_path}')

# TOURISM FEATURE

1= Touristic Region
0= Non Touristic Region

In [ ]:

#  touristic regions
touristic_regions = {'Andalusia', 'Catalonia', 'Valencian Region', 'Madrid', 'Balears', 'Canary Islands'}


merged_final3['touristic_region'] = merged_final3['region'].apply(lambda x: 1 if x in touristic_regions else 0)

<ipython-input-185-1db3831384ca>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
merged_final3.head()

,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,region_standardized_x,region_standardized_y,ipi,touristic_region
year_month,,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,Valencian Region,Valencian Region,81.650,1
2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,Madrid,Madrid,89.055,1
2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,La Rioja,La Rioja,110.747,0
2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,Galicia,Galicia,94.645,0
2014-01-01,Extremadura,64147.55,56911.49,7236.06,NaN,NaN,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,Extremadura,Extremadura,76.387,0

# TOURISM SEASON

In general, the low season is considered to be from November 1 to March 31 and the high season from April 1 to October 31.

However, to be more specific, some hotels and airlines consider the high season to be from November to April and from June 22 to August. The low season is considered to be from April to June 22 and the months of September and October.

Nevertheless, as always, it all depends on where you want to travel. If you are looking for a beach destination, the Canary Islands and the Balearic Islands have good weather all year round without needing to go during the high season, just like the south of the peninsula


Low season = month 11,12,1,2,3
High season= 4, 5,6,7,8 9, 10

source: ChatGPT

In [ ]:
# Function to determine season based on month (modified for index)
def determine_season(timestamp):
    month = timestamp.month  # Extract month directly from Timestamp object
    if month in [11,12,1, 2, 3]:
        return 0
    elif month in [4, 5, 6,7,8, 9, 10]:
        return 1


# Apply the function to create the new feature (using index)
merged_final3['season'] = merged_final3.index.to_series().apply(determine_season)

<ipython-input-187-4c0038df282f>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
merged_final3.head()

,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,region_standardized_x,region_standardized_y,ipi,touristic_region,season
year_month,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,Valencian Region,Valencian Region,81.650,1,0
2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,Madrid,Madrid,89.055,1,0
2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,La Rioja,La Rioja,110.747,0,0
2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,Galicia,Galicia,94.645,0,0
2014-01-01,Extremadura,64147.55,56911.49,7236.06,NaN,NaN,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,Extremadura,Extremadura,76.387,0,0

In [ ]:
# Drive Folder
#csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp_covid_ukrainewar_cpi_ipi_tourism_season.csv'

# csv file for oilconsumption CCAA
#merged_final3.to_csv(csv_file_path, index=True)

#print(f'DataFrame saved successfully to {csv_file_path}')

# Surface _ Registrations Import Dataset

In [ ]:
# Drive Folder
csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/1-FINAL/surface_to_be_built.xlsx'

# second sheet to be uploaded
surface_df = pd.read_excel(csv_file_path)

In [ ]:
surface_df.head()

  year_month             region surface_area_to_build
0 2014-01-01  Castile-La Mancha                    67
1 2014-01-01            Galicia                    25
2 2014-01-01           La Rioja                     6
3 2014-01-01   Valencian Region                    44
4 2014-01-01            Navarre                    12

In [ ]:
# Drop the rows where 'region' is either 'Melilla' or 'Ceuta'
surface_df = surface_df[~surface_df['region'].isin(['Melilla', 'Ceuta'])]

In [ ]:

# Check the unique values in the 'region' column before standardization
unique_regions_before = {
    'merged_final3': merged_final3['region'].unique(),
    'surface_df': surface_df['region'].unique()
}

# Apply the standardization map to both dataframes
merged_final3['region'] = merged_final3['region'].map(standardization_map)
surface_df['region'] = surface_df['region'].map(standardization_map)

# Check the unique values in the 'region' column after standardization
unique_regions_after = {
    'merged_final3': merged_final3['region'].unique(),
    'surface_df': surface_df['region'].unique()
}

# Check for any missing values in the standardized region columns
missing_standardized_merged_final3 = merged_final3[merged_final3['region'].isna()]
missing_standardized_surface_df = surface_df[surface_df['region'].isna()]

# Convert the 'year_month' column in both dataframes to datetime for accurate merging
merged_final3 = merged_final3.reset_index()
merged_final3['year_month'] = pd.to_datetime(merged_final3['year_month'])
surface_df['year_month'] = pd.to_datetime(surface_df['year_month'])

# Remove any additional columns that could cause merge issues
merged_final3 = merged_final3.drop(columns=['region_standardized'], errors='ignore')
surface_df = surface_df.drop(columns=['region_standardized'], errors='ignore')

# Rename columns in surface_df to avoid collision with merged_final3
surface_df_renamed = surface_df.rename(columns=lambda x: f'surface_{x}' if x not in ['year_month', 'region'] else x)

# Merge the dataframes on 'year_month' and 'region' columns
merged_df = pd.merge(merged_final3, surface_df_renamed, on=['year_month', 'region'], how='left')

<ipython-input-193-07493d879f81>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
merged_df.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,region_standardized_x,region_standardized_y,ipi,touristic_region,season,surface_surface_area_to_build
0,2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,Valencian Region,Valencian Region,81.650,1,0,44
1,2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,Madrid,Madrid,89.055,1,0,294
2,2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,La Rioja,La Rioja,110.747,0,0,6
3,2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,Galicia,Galicia,94.645,0,0,25
4,2014-01-01,Extremadura,64147.55,56911.49,7236.06,NaN,NaN,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,Extremadura,Extremadura,76.387,0,0,16

In [ ]:
# Eliminar la columna temporal 'region_standardized' si ya no es necesaria
merged_df.drop(columns=['region_standardized_x','region_standardized_y'], inplace=True)

In [ ]:
merged_df.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,ipi,touristic_region,season,surface_surface_area_to_build
0,2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,81.650,1,0,44
1,2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,89.055,1,0,294
2,2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,110.747,0,0,6
3,2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,94.645,0,0,25
4,2014-01-01,Extremadura,64147.55,56911.49,7236.06,NaN,NaN,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,76.387,0,0,16

In [ ]:
# Drive Folder
#csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp_covid_ukrainewar_cpi_ipi_tourism_season_surface.csv'

# csv file for oilconsumption CCAA
#merged_df.to_csv(csv_file_path, index=True)

#print(f'DataFrame saved successfully to {csv_file_path}')

# Matriculaciones

In [ ]:
# Drive Folder
csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/matriculations_fleetype_region_year_month.csv'

# second sheet to be uploaded
matriculas_df = pd.read_csv(csv_file_path, index_col=False)

In [ ]:
matriculas_df.head()

,Unnamed: 0,region,year_month,Average_Registration_Gasoline,Average_Registration_Diesel
0,0,Andaluc√≠a,2014-01-01,3998,7107
1,1,Andaluc√≠a,2014-02-01,3998,7107
2,2,Andaluc√≠a,2014-03-01,3998,7107
3,3,Andaluc√≠a,2014-04-01,3998,7107
4,4,Andaluc√≠a,2014-05-01,3998,7107

In [ ]:
# Drop the rows where 'region' is either 'Melilla' or 'Ceuta'
matriculas_df = matriculas_df[~matriculas_df['region'].isin(['Melilla (Ciudad Aut√≥noma)', 'Ceuta (Ciudad Aut√≥noma)'])]

In [ ]:
matriculas_df.rename(columns={'Average_Registration_Gasoline':'average_registration_gasoline'}, inplace=True)
matriculas_df.rename(columns={'Average_Registration_Diesel':'average_registration_diesel'}, inplace=True)

In [ ]:
# Elimina la columna "Unnamed: 0"
matriculas_df = matriculas_df.drop("Unnamed: 0", axis=1)

In [ ]:
matriculas_df.head()

,region,year_month,average_registration_gasoline,average_registration_diesel
0,Andaluc√≠a,2014-01-01,3998,7107
1,Andaluc√≠a,2014-02-01,3998,7107
2,Andaluc√≠a,2014-03-01,3998,7107
3,Andaluc√≠a,2014-04-01,3998,7107
4,Andaluc√≠a,2014-05-01,3998,7107

In [ ]:
# Standardization map
standardization_map = {
    # Existing mappings
    'Andalucia': 'Andalusia',
    'Andaluc√≠a': 'Andalusia',
    'Arag√≥n': 'Aragon',
    'Aragon': 'Aragon',
    'Asturias': 'Asturias',
    'Asturias (Principado de)': 'Asturias',
    'Balearic Islands': 'Balearic Islands',
    'BalearicIslands': 'Balearic Islands',
    'Balears (Illes)': 'Balearic Islands',
    'Basque Country': 'Basque Country',
    'BasqueCountry': 'Basque Country',
    'Pa√≠s Vasco': 'Basque Country',
    'Canarias': 'Canary Islands',
    'Canary Islands': 'Canary Islands',
    'CanaryIslands': 'Canary Islands',
    'Castile and Le√≥n': 'Castile and Le√≥n',
    'CastileandLe√≥n': 'Castile and Le√≥n',
    'Castilla y Leon': 'Castile and Le√≥n',
    'Castile-La Mancha': 'Castile-La Mancha',
    'CastileLaMancha': 'Castile-La Mancha',
    'Castilla-La Mancha': 'Castile-La Mancha',
    'Catalu√±a': 'Catalonia',
    'Madrid (Comunidad de)': 'Madrid',
    'Madrid': 'Madrid',
    'La Rioja': 'La Rioja',
    'Rioja (La)': 'La Rioja',
    'Rioja': 'La Rioja',
    'Navarra': 'Navarre',
    'Navarra (Comunidad Foral de)': 'Navarre',
    'Comunitat Valenciana': 'Valencian Region',
    'ValencianCommunity': 'Valencian Region',
    'Valencia': 'Valencian Region',
    'Murcia': 'Murcia',
    'Murcia (Regi√≥n de)': 'Murcia',
    'Andalusia': 'Andalusia',
    'Castile-La Mancha': 'Castilla-La Mancha',
    'Valencian Region': 'Valencian Region',
    'Navarre': 'Navarre',
    'Catalonia': 'Catalonia',
    'Extremadura': 'Extremadura',
    'Cantabria': 'Cantabria',
    'Galicia': 'Galicia',
    'Castile and Leon': 'Castile and Leon',
    # New mappings
    'Asturias, Principado de': 'Asturias',
    'Balears, Illes': 'Balearic Islands',
    'Castilla y Le√≥n': 'Castile and Le√≥n',
    'Castilla - La Mancha': 'Castile-La Mancha',
    'Madrid, Comunidad de': 'Madrid',
    'Murcia, Regi√≥n de': 'Murcia',
    'Navarra, Comunidad Foral de': 'Navarre',
    'Rioja, La': 'La Rioja',
    'Ceuta': 'Ceuta',
    'Melilla': 'Melilla',
    'Comunidad Valenciana': 'Valencian Region',
    'Comunidad de Madrid':'Madrid',
    'Islas Baleares': 'Balearic Islands',
    'Regi√≥n de Murcia': 'Murcia'
}

# Apply the standardization map to both dataframes
merged_df['region'] = merged_df['region'].map(standardization_map)
matriculas_df['region'] = matriculas_df['region'].map(standardization_map)

# Check for any missing values in the standardized region columns
missing_standardized_merged_df = merged_df[merged_df['region'].isna()]
missing_standardized_matriculas_df = matriculas_df[matriculas_df['region'].isna()]

# Convert the 'year_month' column in both dataframes to datetime for accurate merging
merged_df['year_month'] = pd.to_datetime(merged_df['year_month'])
matriculas_df['year_month'] = pd.to_datetime(matriculas_df['year_month'])

# Remove any additional columns that could cause merge issues
merged_df = merged_df.drop(columns=['region_standardized'], errors='ignore')
matriculas_df = matriculas_df.drop(columns=['region_standardized'], errors='ignore')

# Rename columns in matriculas_df to avoid collision with merged_df
matriculas_df_renamed = matriculas_df.rename(columns=lambda x: f'matriculas_{x}' if x not in ['year_month', 'region'] else x)

# Merge the dataframes on 'year_month' and 'region' columns
final_merged_df = pd.merge(merged_df, matriculas_df_renamed, on=['year_month', 'region'], how='left')

# Display counts of NaN values in the region columns after standardization
missing_standardized_merged_df_count = missing_standardized_merged_df.shape[0]
missing_standardized_matriculas_df_count = missing_standardized_matriculas_df.shape[0]

print(f"Number of regions with NaN in merged_df: {missing_standardized_merged_df_count}")
print(f"Number of regions with NaN in matriculas_df: {missing_standardized_matriculas_df_count}")

# Print rows with missing region values for inspection
print("\nRows with missing region in merged_df:")
print(missing_standardized_merged_df)

print("\nRows with missing region in matriculas_df:")
print(missing_standardized_matriculas_df)

# Display the merged dataframe
print("\nFinal Merged DF:")
print(final_merged_df.head())

Number of regions with NaN in merged_df: 0
Number of regions with NaN in matriculas_df: 0

Rows with missing region in merged_df:
Empty DataFrame
Columns: [year_month, region, total_consumption, diesel_consumption, gasoline_consumption, diesel_price, gasoline_price, diesel_withouttaxes, gasoline_withoutaxes, lastbrentprice, apparent_temperature_max, days_holidays, gasoline_fleet, diesel_fleet, UnemRate, IPC, gdp, population, gdp_xcapita, covid_period, ukraine_war_period, ipc_housing, ipc_transport, ipc_tourism, ipi, touristic_region, season, surface_surface_area_to_build]
Index: []

Rows with missing region in matriculas_df:
Empty DataFrame
Columns: [region, year_month, average_registration_gasoline, average_registration_diesel]
Index: []

Final Merged DF:
  year_month            region  total_consumption  diesel_consumption  \
0 2014-01-01  Valencian Region          227804.72           191961.46
1 2014-01-01            Madrid          277389.57           233589.13
2 2014-01-01          La Rioja           24192.97            22164.65
3 2014-01-01           Galicia          215829.82           199103.68
4 2014-01-01       Extremadura           64147.55            56911.49

   gasoline_consumption  diesel_price  gasoline_price  diesel_withouttaxes  \
0              35843.26           NaN             NaN                  NaN
1              43800.44           NaN             NaN                  NaN
2               2028.32           NaN             NaN                  NaN
3              16726.14           NaN             NaN                  NaN
4               7236.06           NaN             NaN                  NaN

   gasoline_withoutaxes lastbrentprice  apparent_temperature_max  \
0                   NaN         106,40                     13.14
1                   NaN         106,40                      6.79
2                   NaN         106,40                      7.77
3                   NaN         106,40                      9.92
4                   NaN         106,40                     11.49

   days_holidays  gasoline_fleet  diesel_fleet  UnemRate  IPC           gdp  \
0            NaN        122184.0      146990.0     28.04  0.1  8.006332e+06
1            2.0        143123.0      206366.0     20.43  0.2  1.614141e+07
2            2.0          6146.0       10014.0     19.58  0.0  6.386617e+05
3            2.0         55402.0      101688.0     23.20  0.4  4.502699e+06
4            2.0         22400.0       40199.0     32.14 -0.1  1.414997e+06

     population  gdp_xcapita  covid_period  ukraine_war_period  ipc_housing  \
0  4.963466e+06  1613.052836             0                   0          0.7
1  6.377936e+06  2530.819929             0                   0          0.2
2  3.162320e+05  2019.598444             0                   0          0.5
3  2.747907e+06  1638.592295             0                   0          0.4
4  1.097298e+06  1289.528897             0                   0          0.6

   ipc_transport  ipc_tourism      ipi  touristic_region  season  \
0           -0.6          0.0   81.650                 1       0
1           -0.5         -0.2   89.055                 1       0
2           -0.6         -1.0  110.747                 0       0
3            0.5         -0.1   94.645                 0       0
4           -0.7         -0.4   76.387                 0       0

  surface_surface_area_to_build  matriculas_average_registration_gasoline  \
0                            44                                    3673.0
1                           294                                    9720.0
2                             6                                     188.0
3                            25                                    1347.0
4                            16                                     417.0

   matriculas_average_registration_diesel
0                                  6529.0
1                                 17280.0
2                                   335.0
3                                  2394.0
4                                   741.0

In [ ]:
final_merged_df.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,ipi,touristic_region,season,surface_surface_area_to_build,matriculas_average_registration_gasoline,matriculas_average_registration_diesel
0,2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,81.650,1,0,44,3673.0,6529.0
1,2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,89.055,1,0,294,9720.0,17280.0
2,2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,110.747,0,0,6,188.0,335.0
3,2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,94.645,0,0,25,1347.0,2394.0
4,2014-01-01,Extremadura,64147.55,56911.49,7236.06,NaN,NaN,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,76.387,0,0,16,417.0,741.0

In [ ]:
# Identify the unique regions in the original matriculas_df that are not present in the standardization map
original_regions_matriculas_df = matriculas_df_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/matriculations_fleetype_region_year_month.csv'

original_regions = pd.read_csv(matriculas_df_path)['region'].unique()

# Identify regions that are not mapped correctly
regions_not_in_standardization_map = [region for region in original_regions if region not in standardization_map]

# Display the regions that are not in the standardization map
regions_not_in_standardization_map

['Ceuta (Ciudad Aut√≥noma)', 'Melilla (Ciudad Aut√≥noma)']

# FINAL MASTER FILE DATASET

In [ ]:
# Drive Folder

csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp_covid_ukrainewar_cpi_ipi_tourism_season_surface_matricula.csv'

# csv file for oilconsumption CCAA
final_merged_df.to_csv(csv_file_path, index=True)

print(f'DataFrame saved successfully to {csv_file_path}')

DataFrame saved successfully to /content/drive/Shareddrives/Capstone - Repsol (Group 3)/Scope Investigation /FILE OUTPUT DATA/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp_covid_ukrainewar_cpi_ipi_tourism_season_surface_matricula.csv

In [ ]:
final_merged_df.head()

,year_month,region,total_consumption,diesel_consumption,gasoline_consumption,diesel_price,gasoline_price,diesel_withouttaxes,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,ipi,touristic_region,season,surface_surface_area_to_build,matriculas_average_registration_gasoline,matriculas_average_registration_diesel
0,2014-01-01,Valencian Region,227804.72,191961.46,35843.26,NaN,NaN,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,81.650,1,0,44,3673.0,6529.0
1,2014-01-01,Madrid,277389.57,233589.13,43800.44,NaN,NaN,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,89.055,1,0,294,9720.0,17280.0
2,2014-01-01,La Rioja,24192.97,22164.65,2028.32,NaN,NaN,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,110.747,0,0,6,188.0,335.0
3,2014-01-01,Galicia,215829.82,199103.68,16726.14,NaN,NaN,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,94.645,0,0,25,1347.0,2394.0
4,2014-01-01,Extremadura,64147.55,56911.49,7236.06,NaN,NaN,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,76.387,0,0,16,417.0,741.0

# FINAL MASTER FILE BY GASOLINE & DIESEL

In [ ]:
csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Repsol Model/FINAL DATASET/FinalMerged_oilcom_prices_weather_holidays_vehicleslandscape_unemrate_ipc_gdp_covid_ukrainewar_cpi_ipi_tourism_season_surface_matricula.csv'


df = pd.read_csv(csv_file_path)

# Crear el conjunto de datos para gasolina eliminando las columnas relacionadas con di√©sel
df_gasoline_full = df.drop(columns=['diesel_consumption', 'diesel_price', 'diesel_withouttaxes'])

# Crear el conjunto de datos para di√©sel eliminando las columnas relacionadas con gasolina
df_diesel_full = df.drop(columns=['gasoline_consumption', 'gasoline_price', 'gasoline_withoutaxes'])

In [ ]:
df_gasoline_full.head()

,Unnamed: 0,year_month,region,total_consumption,gasoline_consumption,gasoline_price,gasoline_withoutaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,ipi,touristic_region,season,surface_surface_area_to_build,matriculas_average_registration_gasoline,matriculas_average_registration_diesel
0,0,2014-01-01,Valencian Region,227804.72,35843.26,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,81.650,1,0,44,3673.0,6529.0
1,1,2014-01-01,Madrid,277389.57,43800.44,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,89.055,1,0,294,9720.0,17280.0
2,2,2014-01-01,La Rioja,24192.97,2028.32,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,110.747,0,0,6,188.0,335.0
3,3,2014-01-01,Galicia,215829.82,16726.14,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,94.645,0,0,25,1347.0,2394.0
4,4,2014-01-01,Extremadura,64147.55,7236.06,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,76.387,0,0,16,417.0,741.0

In [ ]:
# Drive Folder

csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Repsol Model/FINAL DATASET/FinalMerged_gasoline.csv'

# csv file for oilconsumption CCAA
df_gasoline_full.to_csv(csv_file_path, index=True)

print(f'DataFrame saved successfully to {csv_file_path}')

DataFrame saved successfully to /content/drive/Shareddrives/Capstone - Repsol (Group 3)/Repsol Model/FINAL DATASET/FinalMerged_gasoline.csv

In [ ]:
df_diesel_full.head()

,Unnamed: 0,year_month,region,total_consumption,diesel_consumption,diesel_price,diesel_withouttaxes,lastbrentprice,apparent_temperature_max,days_holidays,gasoline_fleet,diesel_fleet,UnemRate,IPC,gdp,population,gdp_xcapita,covid_period,ukraine_war_period,ipc_housing,ipc_transport,ipc_tourism,ipi,touristic_region,season,surface_surface_area_to_build,matriculas_average_registration_gasoline,matriculas_average_registration_diesel
0,0,2014-01-01,Valencian Region,227804.72,191961.46,NaN,NaN,"106,40",13.14,NaN,122184.0,146990.0,28.04,0.1,8.006332e+06,4.963466e+06,1613.052836,0,0,0.7,-0.6,0.0,81.650,1,0,44,3673.0,6529.0
1,1,2014-01-01,Madrid,277389.57,233589.13,NaN,NaN,"106,40",6.79,2.0,143123.0,206366.0,20.43,0.2,1.614141e+07,6.377936e+06,2530.819929,0,0,0.2,-0.5,-0.2,89.055,1,0,294,9720.0,17280.0
2,2,2014-01-01,La Rioja,24192.97,22164.65,NaN,NaN,"106,40",7.77,2.0,6146.0,10014.0,19.58,0.0,6.386617e+05,3.162320e+05,2019.598444,0,0,0.5,-0.6,-1.0,110.747,0,0,6,188.0,335.0
3,3,2014-01-01,Galicia,215829.82,199103.68,NaN,NaN,"106,40",9.92,2.0,55402.0,101688.0,23.20,0.4,4.502699e+06,2.747907e+06,1638.592295,0,0,0.4,0.5,-0.1,94.645,0,0,25,1347.0,2394.0
4,4,2014-01-01,Extremadura,64147.55,56911.49,NaN,NaN,"106,40",11.49,2.0,22400.0,40199.0,32.14,-0.1,1.414997e+06,1.097298e+06,1289.528897,0,0,0.6,-0.7,-0.4,76.387,0,0,16,417.0,741.0

In [ ]:
# Drive Folder

csv_file_path = '/content/drive/Shareddrives/Capstone - Repsol (Group 3)/Repsol Model/FINAL DATASET/FinalMerged_diesel.csv'

# csv file for oilconsumption CCAA
df_diesel_full.to_csv(csv_file_path, index=True)

print(f'DataFrame saved successfully to {csv_file_path}')

DataFrame saved successfully to /content/drive/Shareddrives/Capstone - Repsol (Group 3)/Repsol Model/FINAL DATASET/FinalMerged_diesel.csv